//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class ASATable
    {
        [DisplayName("ID")]
        public string IDAccomp { get; set; }
        [DisplayName("ID")]
        public int IDASA { get; set; }
        [DisplayName("ASA No.")]
        public string ASANo { get; set; }
        [DisplayName("Amount")]
        public Nullable<double> ASAAmount { get; set; }
        public Nullable<System.DateTime> As_Of { get; set; }


        //public int IDASA { get; set; }
        //public string IDAccomp { get; set; }
        //public string ASANo { get; set; }
        //public Nullable<double> ASAAmount { get; set; }
        //public Nullable<System.DateTime> As_Of { get; set; }
    }
}
