//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoWinner
    {
        public int IDwinnderBingo { get; set; }
        public string email { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> datewin { get; set; }
        public Nullable<System.TimeSpan> timewin { get; set; }
        public string title { get; set; }
        public Nullable<int> sixDigit { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string urlwinner { get; set; }
    }
}
