//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoImage
    {
        public int GameID { get; set; }
        public string Gametype { get; set; }
        public string GameImage { get; set; }
        public string GameCode { get; set; }
        public Nullable<int> noballs { get; set; }
    }
}
