//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimateChangeAccomp
    {
        public int IDClimateAccomp { get; set; }
        public Nullable<int> IDClimate { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<double> Phy { get; set; }
        public Nullable<double> Fin { get; set; }
        public string remarks { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string asof { get; set; }
    }
}
