//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ContractStatusView
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string mainproject { get; set; }
        public string maindescription { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public int ContractID { get; set; }
        [DisplayName("Contract Name")]
        public string ContractName { get; set; }
        [DisplayName("Description")]
        public string ContractDescription { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DisplayName("Date")]
        public Nullable<System.DateTime> ContractDate { get; set; }
        [DisplayName("Amount of Contract")]
        public Nullable<double> ContractAmount { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        [DisplayName("Month")]
        public Nullable<int> mnt { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        [DisplayName("Year")]
        public Nullable<int> yr { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        [DisplayName("Target")]
        public Nullable<double> Planned { get; set; }
        public Nullable<double> Revised { get; set; }
        public Nullable<double> Actual { get; set; }
        public string Remarks { get; set; }
        public int ContractStatusID { get; set; }
         [DisplayName("Month")]
        public string ColumnDisplayMonth { get; set; }
        public Nullable<double> TotalPlanned { get; set; }
        public Nullable<double> TotalRevised { get; set; }
        public Nullable<double> TotalActual { get; set; }
        public Nullable<double> TotalPercentContract { get; set; }
        public Nullable<double> TotalContractAmount { get; set; }
        public Nullable<double> PercentofContract { get; set; }
        public monthname ListofMonth { get; set; }
        public string ContractorName { get; set; }
        public Nullable<System.DateTime> TargetStart { get; set; }
        public Nullable<System.DateTime> TargetEnd { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> EstimatedEnd { get; set; }
         [DisplayName("ABC Amount")]
        public Nullable<double> ABCAmount { get; set; }
     //    [Required(ErrorMessage = "This field is Required")]
          [DisplayName("Date")]
        public Nullable<System.DateTime> ActionDate { get; set; }
          [DisplayName("Warning")]
        public string ActionWarning { get; set; }
          public Nullable<int> ContractDuration { get; set; }
          public Nullable<System.DateTime> RevisedExpiryDate { get; set; }
        [DisplayName("Revised 1")]
          public Nullable<double> Revised1 { get; set; }
        [DisplayName("Revised 2")]
          public Nullable<double> Revised2 { get; set; }
        [DisplayName("Revised 3")]
          public Nullable<double> Revised3 { get; set; }
        [DisplayName("Revised 4")]
          public Nullable<double> Revised4 { get; set; }
        [DisplayName("Revised 5")]
          public Nullable<double> Revised5 { get; set; }
        [DisplayName("Revised 6")]
          public Nullable<double> Revised6 { get; set; }
        [DisplayName("Revised 7")]
          public Nullable<double> Revised7 { get; set; }
        [DisplayName("Revised 8")]
          public Nullable<double> Revised8 { get; set; }
        [DisplayName("Revised 9")]
        public Nullable<double> Revised9 { get; set; }
        [DisplayName("Revised 10")]
          public Nullable<double> Revised10 { get; set; }
          public Nullable<double> Revised11 { get; set; }
          public Nullable<double> Revised12 { get; set; }
          public Nullable<double> Revised13 { get; set; }
          public Nullable<double> Revised14 { get; set; }
          public Nullable<double> Revised15 { get; set; }
          public string infra { get; set; }
              [DisplayName("Remarks")]
          public string RemarksContract { get; set; }
              [DisplayName("Contract Reference No.")]
          public string ContractReferenceNo { get; set; }
          public string projectmonitor { get; set; }
          public Nullable<System.DateTime> PhilGepsPositng { get; set; }
          public Nullable<int> ReviseContractDuration { get; set; }
          public Nullable<double> ReviseContractAmount { get; set; }
          public string type { get; set; }
    }


    public enum monthname
    {
        January = 1,
        February = 2,
        March = 3,
        April = 4,
        May = 5,
        June = 6,
        July = 7,
        August = 8,
        September = 9,
        October = 10,
        November = 11,
        December = 12
    }
}
