//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    
    public partial class ContractStatu
    {
        public int ContractStatusID { get; set; }
        public Nullable<int> ContractID { get; set; }
        [DisplayName("Month")]
        public Nullable<int> mnt { get; set; }
        [DisplayName("Year")]
        public Nullable<int> yr { get; set; }
        
        public Nullable<double> Planned { get; set; }
        public Nullable<double> Revised { get; set; }
        public Nullable<double> Actual { get; set; }
        [DataType(DataType.MultilineText)]
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionWarning { get; set; }

        public Nullable<double> Revised1 { get; set; }
        public Nullable<double> Revised2 { get; set; }
        public Nullable<double> Revised3 { get; set; }
        public Nullable<double> Revised4 { get; set; }
        public Nullable<double> Revised5 { get; set; }
        public Nullable<double> Revised6 { get; set; }
        public Nullable<double> Revised7 { get; set; }
        public Nullable<double> Revised8 { get; set; }
        public Nullable<double> Revised9 { get; set; }
        public Nullable<double> Revised10 { get; set; }
        public Nullable<double> Revised11 { get; set; }
        public Nullable<double> Revised12 { get; set; }
        public Nullable<double> Revised13 { get; set; }
        public Nullable<double> Revised14 { get; set; }
        public Nullable<double> Revised15 { get; set; }
    }
}
