//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ContractProfile : IValidatableObject
    {
        //public int ContractID { get; set; }
        //public string ContractName { get; set; }
        //public string ContractDescription { get; set; }
        //public Nullable<System.DateTime> ContractDate { get; set; }
        //public Nullable<double> ContractAmount { get; set; }
        public string IDAccomp { get; set; }


        public int ContractID { get; set; }
         [Required(ErrorMessage = "Enter the Contract Name")]
        [DisplayName("Contract Name")]
        public string ContractName { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("Description")]
        public string ContractDescription { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DisplayName("Date")]
        public Nullable<System.DateTime> ContractDate { get; set; }
        [DisplayName("Amount of Contract")]
        public Nullable<double> ContractAmount { get; set; }
        public string ContractorName { get; set; }
        public Nullable<System.DateTime> TargetStart { get; set; }
        public Nullable<System.DateTime> TargetEnd { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> EstimatedEnd { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public Nullable<System.DateTime> RevisedExpiryDate { get; set; }
        [DisplayName("ABC Amount")]
        public Nullable<double> ABCAmount { get; set; }
        public string RemarksContract { get; set; }
        public string ContractReferenceNo { get; set; }
        public Nullable<System.DateTime> PhilGepsPositng { get; set; }
        public Nullable<int> ReviseContractDuration { get; set; }
        public Nullable<double> ReviseContractAmount { get; set; }
        public Nullable<System.DateTime> dateentered { get; set; }
        public string userid { get; set; }
        public string type { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {

            if ((ContractName == ""))
            {
                yield return new ValidationResult("Invalid Input");
            }




        }



    }





}
