//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractBilling
    {
        public int ContractBillingID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public Nullable<double> AmountBilled { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateEncode { get; set; }
    }
}
