//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DBM
    {
        public string IDAccomp { get; set; }
        public Nullable<int> IDDBM { get; set; }
        [Display(Name = "BIDDED (please put a check if the project is already bidded)")]
        public bool CW_Bidded { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Schedule for bidding (if project is not yet bidded)")]
        public Nullable<System.DateTime> CW_Schedule { get; set; }
        [Display(Name = "Force Account Works (please put a check if the project is under FAW)")]
        public bool FAW { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Supplies bidded (put the date of bidding)")]
        public Nullable<System.DateTime> FAW_Schedule { get; set; }
         [DataType(DataType.MultilineText)]
        [Display(Name = "Remarks")]
        public string remarks { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Bidded)")]
        public Nullable<System.DateTime> bid_date { get; set; }
        public Nullable<bool> POW { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string asof { get; set; }
        public Nullable<int> NoOfPOW { get; set; }
        public Nullable<double> AmountBidded { get; set; }
        public Nullable<double> AmountFAW { get; set; }
        public Nullable<int> UnbiddedNoOfPOW { get; set; }
        public Nullable<double> UnbiddedAmount { get; set; }
     
     
    }
}
