//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
    
    public partial class FileAccompContractView
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string mainproject { get; set; }
        public string maindescription { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public string ContractName { get; set; }
        public string ContractDescription { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<double> ContractAmount { get; set; }
        public Nullable<double> PercentofContract { get; set; }
        public string ContractorName { get; set; }
        public Nullable<System.DateTime> TargetStart { get; set; }
        public Nullable<System.DateTime> TargetEnd { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> EstimatedEnd { get; set; }
        public string infra { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public Nullable<System.DateTime> RevisedExpiryDate { get; set; }
        public Nullable<double> ABCAmount { get; set; }
        public string RemarksContract { get; set; }
        public string ContractReferenceNo { get; set; }
        public string projectmonitor { get; set; }
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public int FileType { get; set; }
        public int IDContract { get; set; }
        [DisplayName("TITLE")]
        public string title { get; set; }
        public string location { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("REMARKS")]
        public string remarks { get; set; }
        public Nullable<System.DateTime> dateupload { get; set; }
        public Nullable<System.TimeSpan> timeupload { get; set; }
    }
}
