//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FinancialOBDView
    {
        public string IDAccomp { get; set; }
        [DisplayName("YEAR")]
        public Nullable<int> year { get; set; }
        [DisplayName("REGION")]
        public string region { get; set; }
        [DisplayName("PROVINCE")]
        public string province { get; set; }
        public string district { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        [DisplayName("MAINPROJECT")]
        public string mainproject { get; set; }
        [DisplayName("SUBPROJECT")]
        public string subproject { get; set; }
        [DisplayName("MUNICIPALITY")]
        public string municipality { get; set; }
        [DisplayName("ALLOCATION (P'000)")]
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public int IDFinance { get; set; }
        [DisplayName("SARO NO.")]
        public string sarono { get; set; }
         [DisplayName("SARO AMOUNT")]
        public Nullable<double> saroamount { get; set; }
         [DisplayName("ASA NO.")]
        public string asano { get; set; }
         [DisplayName("ASA")]
        public Nullable<double> asaamount { get; set; }
        [Key]
        public int IDObd { get; set; }
        [DisplayName("NO.")]
        public string Obligationno { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = false)]
        [DisplayName("OBLIGATION ")]
        public Nullable<double> Obligationamount { get; set; }
        [DisplayName("REMARKS")]
        public string Burno { get; set; }
        [DisplayName("BUR")]
        public Nullable<double> Buramount { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = false)]
        [DisplayName("DISBURSEMENT")]
        public Nullable<double> Disbursement { get; set; }
        [DisplayName("MONTH / YEAR")]
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        [DisplayName("TYPE OF RELEASE")]
        public string TYPERELEASE { get; set; }
        [DisplayName("REFERENCE NO.")]
        public string REFERENCENO { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> asadate { get; set; }
        public Nullable<int> IDNCAADA { get; set; }
        public string NTANO { get; set; }
        public string ADANO { get; set; }
        public string status { get; set; }
        public string maindescription { get; set; }
        public string typefinance { get; set; }
        public string particulars { get; set; }
        [DisplayName("NCA AMOUNT")]
        public Nullable<double> nca { get; set; }
        [DisplayName("Date Entered")]
        public Nullable<System.DateTime> DateEntered { get; set; }
      //   [Required(ErrorMessage = "Date is required")]
        [DisplayName("Date Obligation")]
       public Nullable<System.DateTime> dateOD { get; set; }
         public string OPERATIONREGION { get; set; }
         [DisplayName("Date Disbursement")]
         public Nullable<System.DateTime> dateDis { get; set; }
         [DisplayName("Date Cash")]
         public Nullable<System.DateTime> cashdate { get; set; }
         [DisplayName("CASH AMOUNT")]
         public Nullable<double> cash { get; set; }

    }
}
