//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FinancialOBD
    {
        public string IDAccomp { get; set; }
        public Nullable<int> IDFinance { get; set; }
        public int IDObd { get; set; }
        [DisplayName("NO.")]
        public string Obligationno { get; set; }
         [DisplayName("AMOUNT")]
        public Nullable<double> Obligationamount { get; set; }
         [DisplayName("REMARKS")]
        public string Burno { get; set; }
         [DisplayName("AMOUNT")]
        public Nullable<double> Buramount { get; set; }
         [DisplayName("DISBURSEMENT AMOUNT")]
        public Nullable<double> Disbursement { get; set; }
        [Required]
         [DisplayName("MONTH / YEAR")]
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public Nullable<int> IDNCAADA { get; set; }
        public string status { get; set; }
        [DisplayName("NCA AMOUNT")]
        public Nullable<double> nca { get; set; }
        [DisplayName("Date Entered")]
        public Nullable<System.DateTime> DateEntered { get; set; }
         //[Required(ErrorMessage = "Date is required")]
        [DisplayName("Date Obligation")]
        public Nullable<System.DateTime> dateOD { get; set; }
        [DisplayName("Date Disbursement")]
         public Nullable<System.DateTime> dateDis { get; set; }
        [DisplayName("Date Cash")]
        public Nullable<System.DateTime> cashdate { get; set; }
        [DisplayName("ADA AMOUNT")]
        public Nullable<double> cash { get; set; }
    }
}
