//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FinancialNCAADAView
    {
        public string IDAccomp { get; set; }
        [DisplayName("YEAR")]
        public Nullable<int> year { get; set; }
        [DisplayName("REGION")]
        public string region { get; set; }
        [DisplayName("PROVINCE")]
        public string province { get; set; }
        public string district { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        [DisplayName("MAINPROJECT")]
        public string mainproject { get; set; }
        [DisplayName("SUBPROJECT")]
        public string subproject { get; set; }
        [DisplayName("MUNICIPALITY")]
        public string municipality { get; set; }
        [DisplayName("ALLOCATION (P'000)")]
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public int IDFinance { get; set; }
                [DisplayName("SARO NO.")]
        public string sarono { get; set; }
                [DisplayName("SARO AMOUNT")]
        public Nullable<double> saroamount { get; set; }
                [DisplayName("ASA NO.")]
        public string asano { get; set; }
                [DisplayName("ASA AMOUNT")]
        public Nullable<double> asaamount { get; set; }
        public int IDNCAADA { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> NCADate { get; set; }
        [DisplayName("NCA NO.")]
        public string NCANO { get; set; }
        [DisplayName("AMOUNT")]
        public Nullable<double> NCAAmount { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> NTADate { get; set; }
        [DisplayName("NTA NO.")]
        public string NTANO { get; set; }
        [DisplayName("AMOUNT")]
        public Nullable<double> NTAAmount { get; set; }
        [DisplayName("VALIDITY")]
        public Nullable<System.DateTime> Validity { get; set; }
        [DisplayName("COVERING")]
        [DataType(DataType.MultilineText)]
        public string Covering { get; set; }
        [DisplayName("ACCOUNT NO.")]
        public string AccountNo { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> ADADate { get; set; }
        [DisplayName("ADA NO.")]
        public string ADANO { get; set; }
        [DisplayName("AMOUNT")]
        public Nullable<double> ADAAmount { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> asadate { get; set; }
        public string blnk { get; set; }
        public string maindescription { get; set; }
        public string typefinance { get; set; }
        public string particulars { get; set; }
    }
}
