//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialASAAttachment
    {
        public string ASANO { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATH { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public int id { get; set; }
        public string status { get; set; }
        public string region { get; set; }
    }
}
