//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSDEContractStudy
    {
        public int IDStudy { get; set; }
        public string IDAccomp { get; set; }
        public string TypeofStudy { get; set; }
        public Nullable<int> Consultant { get; set; }
    }
}
