//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSDEPhysical
    {
        public string IDAccomp { get; set; }
        public int IdFSDE { get; set; }
        public string typeofStudy { get; set; }
        public string modeImplementation { get; set; }
        public Nullable<System.DateTime> dateNTP { get; set; }
        public Nullable<System.DateTime> ActivityStart { get; set; }
        public Nullable<System.DateTime> ActivityFinish { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string asof { get; set; }
        public string remarks { get; set; }
        public Nullable<int> startConstruction { get; set; }
        public Nullable<double> valueaccompfs { get; set; }
        public Nullable<double> valueaccompde { get; set; }
        public Nullable<double> expendituresfs { get; set; }
        public Nullable<double> expendituresde { get; set; }
        public Nullable<double> physicalfs { get; set; }
        public Nullable<double> physicalde { get; set; }
        public Nullable<double> financialfs { get; set; }
        public Nullable<double> financialde { get; set; }
        public Nullable<double> fsobligation { get; set; }
        public Nullable<double> deobligation { get; set; }
    }
}
