//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplementationAndCoordinate
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string subproject { get; set; }
        public string maindescription { get; set; }
        public string projectmonitor { get; set; }
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string statusProject { get; set; }
        public string remarksAccomp { get; set; }
        public Nullable<double> Physical { get; set; }
        public Nullable<double> Financial { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string ACTIVITY { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> OBLIGATION { get; set; }
        public double DISBURSEMENT { get; set; }
        public Nullable<double> SARO { get; set; }
        public string CONTRACTORNAME { get; set; }
        public string TARGETSTART { get; set; }
        public string TARGETEND_ { get; set; }
        public string ESTIMATEDEND { get; set; }
        public string ACTUALSTART { get; set; }
        public string Category4 { get; set; }
        public string infra { get; set; }
        public Nullable<double> ValueAccomp { get; set; }
        public Nullable<double> Expenditures { get; set; }
        public Nullable<int> SORT { get; set; }
    }
}
