//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_ConAct
    {
        public string IDAccomp { get; set; }
        public Nullable<int> act_NoIA_TARGET { get; set; }
        public Nullable<int> act_Batches_TARGET { get; set; }
        public Nullable<int> act_Participants_TARGET { get; set; }
        public Nullable<int> act_NoIA { get; set; }
        public Nullable<int> act_Batches_Covered { get; set; }
        public Nullable<int> act_Participants { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idaa { get; set; }
        public Nullable<double> act_cost { get; set; }
        public Nullable<double> act_cost_target { get; set; }
    }
}
