//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using AccompProject.Models.EntityModel;
    using AccompProject.Models;
    using System.Linq;
    using System.Web;
     using System.Web.Mvc;

    
    public partial class IMTSSViewModelPhysical
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public int ParticularsId { get; set; }
         [DisplayName("PARTICULARS")]
        public string Particulars { get; set; }
        public Nullable<int> SubParticularsID { get; set; }
         [DisplayName("SUBPARTICULARS")]
        public string SubParticulars { get; set; }
        public int SubSubParticularsId { get; set; }
      [DisplayName("OTHER PARTICULARS")]
        public string SubSubParticulars { get; set; }
         [DisplayName("TARGET FOR THE YEAR")]
        public Nullable<double> total_for_year { get; set; }
         [DisplayName("TARGET FOR THE MONTH")]
        public Nullable<double> target_actual { get; set; }
         [DisplayName("ACTUAL ACCOMPLISHMENT")]
        public Nullable<double> accomp_actual { get; set; }
        public string quarter { get; set; }
        public int imtssID { get; set; }


       

    }
}
