//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class IMTSSViewModel
    {
        public string IDACCOMP { get; set; }
        public Nullable<int> MNT { get; set; }
        public Nullable<int> YEAR_COVERED { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> Allotment { get; set; }
        public Nullable<double> amount { get; set; }
         [DisplayName("b. Daily")]
        public Nullable<int> dailyjob_TARGET { get; set; }
         [DisplayName("c. Contractual")]
        public Nullable<int> Contractual_TARGET { get; set; }
        public Nullable<int> dailyjob { get; set; }
        public Nullable<int> Contractual { get; set; }
         [DisplayName("a. No. of IA")]
        public Nullable<int> Org_NoIA_TARGET { get; set; }
         [DisplayName("b. Area Covered (ha)")]
        public Nullable<double> Org_Area_Covered_TARGET { get; set; }
         [DisplayName("c. No of FBs")]
        public Nullable<int> Org_NoFB_TARGET { get; set; }
        public Nullable<int> Org_NoIA { get; set; }
        public Nullable<double> Org_Area_Covered { get; set; }
        public Nullable<int> Org_NoFB { get; set; }
          [DisplayName("a. No. of IA")]
        public Nullable<int> Reg_NoIA_TARGET { get; set; }
          [DisplayName("b. Area Covered (ha)")]
        public Nullable<double> Reg_Area_Covered_TARGET { get; set; }
         [DisplayName("c. No of FBs")]
        public Nullable<int> Reg_NoFB_TARGET { get; set; }
        public Nullable<int> Reg_NoIA { get; set; }
        public Nullable<double> Reg_Area_Covered { get; set; }
        public Nullable<int> Reg_NoFB { get; set; }
         [DisplayName("a. No. of IA")]
        public Nullable<int> Str_NoIA_TARGET { get; set; }
          [DisplayName("b. No. of TSAGs/FIGs")]
        public Nullable<int> Str_Tsag_TARGET { get; set; }
        public Nullable<int> Str_Tsag { get; set; }
         [DisplayName("c. Area Covered (ha)")]
        public Nullable<double> Str_Area_Covered_TARGET { get; set; }
         [DisplayName("d. No of FBs")]
        public Nullable<int> Str_NoFB_TARGET { get; set; }
        public Nullable<int> Str_NoIA { get; set; }
        public Nullable<double> Str_Area_Covered { get; set; }
        public Nullable<int> Str_NoFB { get; set; }
          [DisplayName("a. No. of IA")]
        public Nullable<int> Sus_NoIA_TARGET { get; set; }
        [DisplayName("b. No. of TSAGs/FIGs")]
        public Nullable<int> Sus_Tsag_TARGET { get; set; }
        public Nullable<int> Sus_Tsag { get; set; }
         [DisplayName("c. Area Covered (ha)")]
        public Nullable<double> Sus_Area_Covered_TARGET { get; set; }
         [DisplayName("d. No of Members")]
        public Nullable<int> Sus_NoFB_TARGET { get; set; }
        public Nullable<int> Sus_NoIA { get; set; }
        public Nullable<double> Sus_Area_Covered { get; set; }
        public Nullable<int> Sus_NoFB { get; set; }
          [DisplayName("a. No. of IA")]
        public Nullable<int> CapacityIA_NoIA_TARGET { get; set; }
          [DisplayName("b. No. of Batches")]
        public Nullable<int> CapacityIA_Batches_TARGET { get; set; }
          [DisplayName("c. No. of Participants")]
        public Nullable<int> CapacityIA_Participants_TARGET { get; set; }
        public Nullable<int> CapacityIA_NoIA { get; set; }
        public Nullable<int> CapacityIA_Batches_Covered { get; set; }
        public Nullable<int> CapacityIA_Participants { get; set; }
         [DisplayName("a. No. of Batches")]
        public Nullable<int> CapacityStaff_Batches_TARGET { get; set; }
           [DisplayName("b. No. of Participants")]
        public Nullable<int> CapacityStaff_Participants_TARGET { get; set; }
        public Nullable<int> CapacityStaff_Batches_Covered { get; set; }
        public Nullable<int> CapacityStaff_Participants { get; set; }
            [DisplayName("a. No. of IA")]
        public Nullable<int> Assist_NoIA_TARGET { get; set; }
         [DisplayName("b. No. of Batches")]
        public Nullable<int> Assist_Batches_TARGET { get; set; }
         [DisplayName("c. No. of Participants")]
        public Nullable<int> Assist_Participants_TARGET { get; set; }
        public Nullable<int> Assist_NoIA { get; set; }
        public Nullable<int> Assist_Batches_Covered { get; set; }
        public Nullable<int> Assist_Participants { get; set; }
        public int ida { get; set; }
        public int idb { get; set; }
        public int idc { get; set; }
        public int idd { get; set; }
        public int ide { get; set; }
        public int idf { get; set; }
        public int idg { get; set; }
        public int idh { get; set; }
        public Nullable<double> COST_TARGET { get; set; }
        public Nullable<double> COST_ACCOMP { get; set; }
          [DisplayName("a. No. of IAs")]
        public Nullable<double> CapacityIAWORKSHOP_COST_TARGET { get; set; }
        [DisplayName("b. No. of Batches")]
        public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET { get; set; }
          [DisplayName("c. No. of Participants")]
        public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET { get; set; }
        public Nullable<double> CapacityIAWORKSHOP_COST { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Batches_Covered { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Participants { get; set; }
        [DisplayName("FOR THE MONTH")]
        public string AS_OF { get; set; }
        public int idcC { get; set; }
          [DisplayName("a. No. of Batches")]
        public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET { get; set; }
         [DisplayName("b. No. of Participants")]
        public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Batches_Covered { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Participants { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET { get; set; }
        public int idbB { get; set; }
        public Nullable<double> CapacityStaff_COST_TARGET { get; set; }
        public Nullable<double> CapacityStaff_COST { get; set; }
        public Nullable<double> CapacityIA_COST { get; set; }
        public Nullable<double> CapacityIA_COST_TARGET { get; set; }
        public Nullable<double> Assist_cost { get; set; }
        public Nullable<double> Assist_cost_target { get; set; }
        public int IMTSSID { get; set; }

        public Nullable<int> joborder { get; set; }
         [DisplayName("a. Job Order")]
        public Nullable<int> joborder_target { get; set; }
         [DisplayName("d. No of Members")]
        public Nullable<int> Org_NoMember_Target { get; set; }
        public Nullable<int> Org_NoMember { get; set; }
         [DisplayName("d. No of Members")]
        public Nullable<int> Reg_NoMember_Target { get; set; }
        public Nullable<int> Reg_NoMember { get; set; }
          [DisplayName("a. No. of IA")]
        public Nullable<int> ModOther_NoIA_TARGET { get; set; }
         [DisplayName("b. Area Covered (ha)")]
        public Nullable<double> ModOther_Area_Covered_TARGET { get; set; }
           [DisplayName("c. No of FBs")]
        public Nullable<int> ModOther_NoFB_TARGET { get; set; }
        public Nullable<int> ModOther_NoIA { get; set; }
        public Nullable<double> ModOther_Area_Covered { get; set; }
        public Nullable<int> ModOther_NoFB { get; set; }
          [DisplayName("d. No of Members")]
        public Nullable<int> ModOther_NoMember_Target { get; set; }
        public Nullable<int> ModOther_NoMember { get; set; }
        public int iddMod { get; set; }
        public Nullable<double> ModOther_unlined_target { get; set; }
        public Nullable<double> ModOther_unlined { get; set; }
        public Nullable<double> ModOther_lined_target { get; set; }
        public Nullable<double> ModOther_lined { get; set; }
          [DisplayName("a. No. of IA")]
        public Nullable<int> ModCon_NoIA_TARGET { get; set; }
         [DisplayName("b. Area Covered (ha)")]
        public Nullable<double> ModCon_Area_Covered_TARGET { get; set; }
             [DisplayName("c. No of FBs")]
        public Nullable<int> ModCon_NoFB_TARGET { get; set; }
        public Nullable<int> ModCon_NoIA { get; set; }
        public Nullable<double> ModCon_Area_Covered { get; set; }
        public Nullable<int> ModCon_NoFB { get; set; }
           [DisplayName("d. No of Members")]
        public Nullable<int> ModCon_NoMember_Target { get; set; }
        public Nullable<int> ModCon_NoMember { get; set; }
        public int iddModCon { get; set; }
           [DisplayName("e.1. Unlined Canals")]
        public Nullable<double> ModCon_unlined_target { get; set; }
        public Nullable<double> ModCon_unlined { get; set; }
        public Nullable<double> ModCon_lined { get; set; }
         [DisplayName("e.2. Lined Canals")]
        public Nullable<double> ModCon_lined_target { get; set; }

         public Nullable<double> ModCon_SA { get; set; }
          [DisplayName("Service Area (ha)")]
         public Nullable<double> ModCon_SA_target { get; set; }
         public Nullable<double> ModCon_FUSA { get; set; }
          [DisplayName("FUSA (ha)")]
         public Nullable<double> ModCon_FUSA_target { get; set; }
         [DataType(DataType.MultilineText)]
          [DisplayName("Remarks")]
         public string ModCon_Remarks { get; set; }

         [DisplayName("a. No. of IA")]
         public Nullable<int> EModCon_NoIA_TARGET { get; set; }
         [DisplayName("b. Area Covered (ha)")]
         public Nullable<double> EModCon_Area_Covered_TARGET { get; set; }
         [DisplayName("c. No of FBs")]
         public Nullable<int> EModCon_NoFB_TARGET { get; set; }
         public Nullable<int> EModCon_NoIA { get; set; }
         public Nullable<double> EModCon_Area_Covered { get; set; }
         public Nullable<int> EModCon_NoFB { get; set; }
         [DisplayName("d. No of Members")]
         public Nullable<int> EModCon_NoMember_Target { get; set; }
         public Nullable<int> EModCon_NoMember { get; set; }
         public int iddEModCon { get; set; }
         [DisplayName("e.1. Unlined Canals")]
         public Nullable<double> EModCon_unlined_target { get; set; }
         public Nullable<double> EModCon_unlined { get; set; }
         public Nullable<double> EModCon_lined { get; set; }
         [DisplayName("e.2. Lined Canals")]
         public Nullable<double> EModCon_lined_target { get; set; }

         public Nullable<double> EModCon_SA { get; set; }
         [DisplayName("Service Area (ha)")]
         public Nullable<double> EModCon_SA_target { get; set; }
         public Nullable<double> EModCon_FUSA { get; set; }
         [DisplayName("FUSA (ha)")]
         public Nullable<double> EModCon_FUSA_target { get; set; }
        [DisplayName("e. No of Members")]
         public Nullable<int> Str_NoMember_TARGET { get; set; }
         public Nullable<int> Str_NoMember { get; set; }
        [DisplayName("e. No of FB")]
         public Nullable<int> Sus_NoFB1_TARGET { get; set; }
         public Nullable<int> Sus_NoFB1 { get; set; }



         public Nullable<int> Str_NoIA_TARGET1 { get; set; }
         public Nullable<int> Str_Tsag_TARGET1 { get; set; }
         public Nullable<double> Str_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> Str_NoFB_TARGET1 { get; set; }
         public Nullable<int> Str_NoMember_TARGET1 { get; set; }
         public Nullable<int> Str_NoIA_TARGET2 { get; set; }
         public Nullable<int> Str_Tsag_TARGET2 { get; set; }
         public Nullable<double> Str_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> Str_NoFB_TARGET2 { get; set; }
         public Nullable<int> Str_NoMember_TARGET2 { get; set; }
         public Nullable<int> Sus_NoIA_TARGET1 { get; set; }
         public Nullable<int> Sus_Tsag_TARGET1 { get; set; }
         public Nullable<double> Sus_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> Sus_NoFB_TARGET1 { get; set; }
         public Nullable<int> Sus_NoFB1_TARGET1 { get; set; }
         public Nullable<int> Sus_NoIA_TARGET2 { get; set; }
         public Nullable<int> Sus_Tsag_TARGET2 { get; set; }
         public Nullable<double> Sus_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> Sus_NoFB_TARGET2 { get; set; }
         public Nullable<int> Sus_NoFB1_TARGET2 { get; set; }
         public Nullable<int> CapacityStaff_Batches_TARGET1 { get; set; }
         public Nullable<int> CapacityStaff_Participants_TARGET1 { get; set; }
         public Nullable<double> CapacityStaff_COST_TARGET1 { get; set; }
         public Nullable<int> CapacityStaff_Batches_TARGET2 { get; set; }
         public Nullable<int> CapacityStaff_Participants_TARGET2 { get; set; }
         public Nullable<double> CapacityStaff_COST_TARGET2 { get; set; }
         public Nullable<int> dailyjob_TARGET1 { get; set; }
         public Nullable<int> Contractual_TARGET1 { get; set; }
         public Nullable<double> COST_TARGET1 { get; set; }
         public Nullable<int> joborder_target1 { get; set; }
         public Nullable<int> dailyjob_TARGET2 { get; set; }
         public Nullable<int> Contractual_TARGET2 { get; set; }
         public Nullable<double> COST_TARGET2 { get; set; }
         public Nullable<int> joborder_target2 { get; set; }
         public Nullable<int> CapacityIA_NoIA_TARGETAnnual { get; set; }
         public Nullable<int> CapacityIA_Batches_TARGETAnnual { get; set; }
         public Nullable<int> CapacityIA_Participants_TARGETAnnual { get; set; }
         public Nullable<double> CapacityIA_COST_TARGETAnnual { get; set; }
         public Nullable<int> CapacityIA_NoIA_TARGETRevised { get; set; }
         public Nullable<int> CapacityIA_Batches_TARGETRevised { get; set; }
         public Nullable<int> CapacityIA_Participants_TARGETRevised { get; set; }
         public Nullable<double> CapacityIA_COST_TARGETRevised { get; set; }
         public Nullable<int> Assist_NoIA_TARGETAnnual { get; set; }
         public Nullable<int> Assist_Batches_TARGETAnnual { get; set; }
         public Nullable<int> Assist_Participants_TARGETAnnual { get; set; }
         public Nullable<double> Assist_cost_targetAnnual { get; set; }
         public Nullable<int> Assist_NoIA_TARGETRevised { get; set; }
         public Nullable<int> Assist_Batches_TARGETRevised { get; set; }
         public Nullable<int> Assist_Participants_TARGETRevised { get; set; }
         public Nullable<double> Assist_cost_targetRevised { get; set; }
         public Nullable<int> Org_NoIA_TARGET1 { get; set; }
         public Nullable<double> Org_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> Org_NoFB_TARGET1 { get; set; }
         public Nullable<int> Org_NoMember_Target1 { get; set; }
         public Nullable<int> Org_NoIA_TARGET2 { get; set; }
         public Nullable<double> Org_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> Org_NoFB_TARGET2 { get; set; }
         public Nullable<int> Org_NoMember_Target2 { get; set; }
         public Nullable<int> Reg_NoIA_TARGET1 { get; set; }
         public Nullable<double> Reg_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> Reg_NoFB_TARGET1 { get; set; }
         public Nullable<int> Reg_NoMember_Target1 { get; set; }
         public Nullable<int> Reg_NoIA_TARGET2 { get; set; }
         public Nullable<double> Reg_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> Reg_NoFB_TARGET2 { get; set; }
         public Nullable<int> Reg_NoMember_Target2 { get; set; }
         public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET1 { get; set; }
         public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET1 { get; set; }
         public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET1 { get; set; }
         public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET2 { get; set; }
         public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET2 { get; set; }
         public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET2 { get; set; }
         public Nullable<int> ModOther_NoIA_TARGET1 { get; set; }
         public Nullable<double> ModOther_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> ModOther_NoFB_TARGET1 { get; set; }
         public Nullable<int> ModOther_NoMember_Target1 { get; set; }
         public Nullable<double> ModOther_unlined_target1 { get; set; }
         public Nullable<double> ModOther_lined_target1 { get; set; }
         public Nullable<int> ModOther_NoIA_TARGET2 { get; set; }
         public Nullable<double> ModOther_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> ModOther_NoFB_TARGET2 { get; set; }
         public Nullable<int> ModOther_NoMember_Target2 { get; set; }
         public Nullable<double> ModOther_unlined_target2 { get; set; }
         public Nullable<double> ModOther_lined_target2 { get; set; }
         public Nullable<int> EModCon_NoIA_TARGET1 { get; set; }
         public Nullable<double> EModCon_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> EModCon_NoFB_TARGET1 { get; set; }
         public Nullable<int> EModCon_NoMember_Target1 { get; set; }
         public Nullable<double> EModCon_unlined_target1 { get; set; }
         public Nullable<double> EModCon_lined_target1 { get; set; }
         public Nullable<double> EModCon_SA_target1 { get; set; }
         public Nullable<double> EModCon_FUSA_target1 { get; set; }
         public Nullable<int> EModCon_NoIA_TARGET2 { get; set; }
         public Nullable<double> EModCon_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> EModCon_NoFB_TARGET2 { get; set; }
         public Nullable<int> EModCon_NoMember_Target2 { get; set; }
         public Nullable<double> EModCon_unlined_target2 { get; set; }
         public Nullable<double> EModCon_lined_target2 { get; set; }
         public Nullable<double> EModCon_SA_target2 { get; set; }
         public Nullable<double> EModCon_FUSA_target2 { get; set; }
         public Nullable<int> ModCon_NoIA_TARGET1 { get; set; }
         public Nullable<double> ModCon_Area_Covered_TARGET1 { get; set; }
         public Nullable<int> ModCon_NoFB_TARGET1 { get; set; }
         public Nullable<int> ModCon_NoMember_Target1 { get; set; }
         public Nullable<double> ModCon_unlined_target1 { get; set; }
         public Nullable<double> ModCon_lined_target1 { get; set; }
         public Nullable<double> ModCon_SA_target1 { get; set; }
         public Nullable<double> ModCon_FUSA_target1 { get; set; }
         public Nullable<int> ModCon_NoIA_TARGET2 { get; set; }
         public Nullable<double> ModCon_Area_Covered_TARGET2 { get; set; }
         public Nullable<int> ModCon_NoFB_TARGET2 { get; set; }
         public Nullable<int> ModCon_NoMember_Target2 { get; set; }
         public Nullable<double> ModCon_unlined_target2 { get; set; }
         public Nullable<double> ModCon_lined_target2 { get; set; }
         public Nullable<double> ModCon_SA_target2 { get; set; }
         public Nullable<double> ModCon_FUSA_target2 { get; set; }
         public string QUARTER { get; set; }
         public Nullable<double> CapacityIAWORKSHOP_COST_TARGET1 { get; set; }
         public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET1 { get; set; }
         public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET1 { get; set; }
         public Nullable<double> CapacityIAWORKSHOP_COST_TARGET2 { get; set; }
         public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET2 { get; set; }
         public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET2 { get; set; }
         public string maindescription { get; set; }
         public string FUNDS { get; set; }
    }
}
