//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class IMTSSViewModelFinancial
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public int ParticularsId { get; set; }
        [DisplayName("PARTICULARS")]
        public string Particulars { get; set; }
        public int FinancialParticularsId { get; set; }
    [DisplayName("SUBPARTICULARS")]
        public string FinancialParticulars { get; set; }
        [DisplayName("TOTAL BUDGET")]
        public Nullable<double> Total_budget { get; set; }
        [DisplayName("TOTAL EXPENSE")]
        public Nullable<double> Total_Expenses { get; set; }
        public string quarter { get; set; }
        
        public int imtssFinancialID { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<int> mnt { get; set; }
    }
}
