//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class IMTSS_Finance_View
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public string maindescription { get; set; }
        public string projectmonitor { get; set; }
        public string infra { get; set; }
        public string financeRegion { get; set; }
        public string OperationRegion { get; set; }
        public string imo { get; set; }
        public int IDIMTSS_FINANCE { get; set; }
        [DisplayName("FOR THE MONTH")]
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        [DisplayName("Capacity Building For IA")]
        public Nullable<double> CapacityBuildingForIA { get; set; }
        [DisplayName("Capacity Building For NIA Staff")]
        public Nullable<double> CapacityBuildingForNIAStaff { get; set; }
        [DisplayName("Assistance Program")]
        public Nullable<double> AssistanceProgram { get; set; }
        [DisplayName("Supervision Cost")]
        public Nullable<double> SupervisionCost { get; set; }
        [DisplayName("Office Supplies Materials")]
        public Nullable<double> OfficeSuppliesMaterials { get; set; }
        [DisplayName("Miscellaneous")]
        public Nullable<double> Miscellaneous { get; set; }
        [DisplayName("FSS")]
        public Nullable<double> FSS { get; set; }
        [DisplayName("DBMS")]
        public Nullable<double> DBMS { get; set; }
        [DisplayName("Other MOOE")]
        public Nullable<double> OtherMOOE { get; set; }
        [DisplayName("Job Order")]
        public Nullable<double> JobOrder { get; set; }
        [DisplayName("Daily")]
        public Nullable<double> Daily { get; set; }
        [DisplayName("Contractual")]
        public Nullable<double> Contractual { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("Remarks")]
        public string remarks { get; set; }
        public Nullable<double> CapacityBuildingForIAAllocation { get; set; }
        public Nullable<double> CapacityBuildingForNIAStaffAllocation { get; set; }
        public Nullable<double> AssistanceProgramAllocation { get; set; }
        public Nullable<double> SupervisionCostAllocation { get; set; }
        public Nullable<double> OfficeSuppliesMaterialsAllocation { get; set; }
        public Nullable<double> MiscellaneousAllocation { get; set; }
        public Nullable<double> FSSAllocation { get; set; }
        public Nullable<double> DBMSAllocation { get; set; }
        public Nullable<double> OtherMOOEAllocation { get; set; }
        public Nullable<double> JobOrderAllocation { get; set; }
        public Nullable<double> DailyAllocation { get; set; }
        public Nullable<double> ContractualAllocation { get; set; }
        public string FUNDS { get; set; }
        public string QUARTER { get; set; }
        public int SORT { get; set; }

    }
}
