//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_EModContract
    {
        public string IDAccomp { get; set; }
        public Nullable<int> EModCon_NoIA_TARGET { get; set; }
        public Nullable<double> EModCon_Area_Covered_TARGET { get; set; }
        public Nullable<int> EModCon_NoFB_TARGET { get; set; }
        public Nullable<int> EModCon_NoIA { get; set; }
        public Nullable<double> EModCon_Area_Covered { get; set; }
        public Nullable<int> EModCon_NoFB { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public Nullable<int> EModCon_NoMember_Target { get; set; }
        public Nullable<int> EModCon_NoMember { get; set; }
        public int iddEModCon { get; set; }
        public Nullable<double> EModCon_unlined_target { get; set; }
        public Nullable<double> EModCon_unlined { get; set; }
        public Nullable<double> EModCon_lined_target { get; set; }
        public Nullable<double> EModCon_lined { get; set; }
        public Nullable<double> EModCon_SA { get; set; }
        public Nullable<double> EModCon_SA_target { get; set; }
        public Nullable<double> EModCon_FUSA { get; set; }
        public Nullable<double> EModCon_FUSA_target { get; set; }
        public string EModCon_Remarks { get; set; }
        public Nullable<int> EModCon_NoIA_TARGET1 { get; set; }
        public Nullable<double> EModCon_Area_Covered_TARGET1 { get; set; }
        public Nullable<int> EModCon_NoFB_TARGET1 { get; set; }
        public Nullable<int> EModCon_NoMember_Target1 { get; set; }
        public Nullable<double> EModCon_unlined_target1 { get; set; }
        public Nullable<double> EModCon_lined_target1 { get; set; }
        public Nullable<double> EModCon_SA_target1 { get; set; }
        public Nullable<double> EModCon_FUSA_target1 { get; set; }
        public Nullable<int> EModCon_NoIA_TARGET2 { get; set; }
        public Nullable<double> EModCon_Area_Covered_TARGET2 { get; set; }
        public Nullable<int> EModCon_NoFB_TARGET2 { get; set; }
        public Nullable<int> EModCon_NoMember_Target2 { get; set; }
        public Nullable<double> EModCon_unlined_target2 { get; set; }
        public Nullable<double> EModCon_lined_target2 { get; set; }
        public Nullable<double> EModCon_SA_target2 { get; set; }
        public Nullable<double> EModCon_FUSA_target2 { get; set; }
    }
}
