//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS
    {
        public string IDACCOMP { get; set; }
        public Nullable<int> MNT { get; set; }
        public Nullable<int> YEAR_COVERED { get; set; }
        public int IMTSSID { get; set; }
        public string AS_OF { get; set; }
    }
}
