//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSSFinancialViewModel
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> CapacityIA { get; set; }
        public Nullable<double> CapacityStaff { get; set; }
        public Nullable<double> AssistPrograms { get; set; }
        public Nullable<double> SupervisionCost { get; set; }
        public Nullable<double> Supplies { get; set; }
        public Nullable<double> Misc { get; set; }
        public Nullable<double> CapacityIA_budget { get; set; }
        public Nullable<double> CapacityStaff_budget { get; set; }
        public Nullable<double> AssistPrograms_budget { get; set; }
        public Nullable<double> SupervisionCost_budget { get; set; }
        public Nullable<double> Supplies_budget { get; set; }
        public Nullable<double> Misc_budget { get; set; }
        public Nullable<double> salaries { get; set; }
        public Nullable<double> remunerations { get; set; }
        public Nullable<double> salaries_budget { get; set; }
        public Nullable<double> remunerations_budget { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
    }
}
