//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_Assistance
    {
        public string IDAccomp { get; set; }
        public Nullable<int> Assist_NoIA_TARGET { get; set; }
        public Nullable<int> Assist_Batches_TARGET { get; set; }
        public Nullable<int> Assist_Participants_TARGET { get; set; }
        public Nullable<int> Assist_NoIA { get; set; }
        public Nullable<int> Assist_Batches_Covered { get; set; }
        public Nullable<int> Assist_Participants { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int ida { get; set; }
        public Nullable<double> Assist_cost { get; set; }
        public Nullable<double> Assist_cost_target { get; set; }
        public Nullable<int> Assist_NoIA_TARGETAnnual { get; set; }
        public Nullable<int> Assist_Batches_TARGETAnnual { get; set; }
        public Nullable<int> Assist_Participants_TARGETAnnual { get; set; }
        public Nullable<double> Assist_cost_targetAnnual { get; set; }
        public Nullable<int> Assist_NoIA_TARGETRevised { get; set; }
        public Nullable<int> Assist_Batches_TARGETRevised { get; set; }
        public Nullable<int> Assist_Participants_TARGETRevised { get; set; }
        public Nullable<double> Assist_cost_targetRevised { get; set; }
    }
}
