//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_CapacityStaffWORKSHOP
    {
        public string IDAccomp { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Batches_Covered { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Participants { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idbB { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET1 { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET1 { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET1 { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Batches_TARGET2 { get; set; }
        public Nullable<int> CapacityStaffWORKSHOP_Participants_TARGET2 { get; set; }
        public Nullable<double> CapacityStaffWORKSHOP_COST_TARGET2 { get; set; }
    }
}
