//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_IDPPersonnel
    {
        public string IDAccomp { get; set; }
        public Nullable<int> dailyjob_TARGET { get; set; }
        public Nullable<int> Contractual_TARGET { get; set; }
        public Nullable<int> dailyjob { get; set; }
        public Nullable<int> Contractual { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idh { get; set; }
        public Nullable<double> COST_TARGET { get; set; }
        public Nullable<double> COST_ACCOMP { get; set; }
        public Nullable<int> joborder { get; set; }
        public Nullable<int> joborder_target { get; set; }
        public Nullable<int> dailyjob_TARGET1 { get; set; }
        public Nullable<int> Contractual_TARGET1 { get; set; }
        public Nullable<double> COST_TARGET1 { get; set; }
        public Nullable<int> joborder_target1 { get; set; }
        public Nullable<int> dailyjob_TARGET2 { get; set; }
        public Nullable<int> Contractual_TARGET2 { get; set; }
        public Nullable<double> COST_TARGET2 { get; set; }
        public Nullable<int> joborder_target2 { get; set; }
    }
}
