//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class IMTSS_ModContract
    {
        public string IDAccomp { get; set; }
        public Nullable<int> ModCon_NoIA_TARGET { get; set; }
        public Nullable<double> ModCon_Area_Covered_TARGET { get; set; }
        public Nullable<int> ModCon_NoFB_TARGET { get; set; }
        public Nullable<int> ModCon_NoIA { get; set; }
        public Nullable<double> ModCon_Area_Covered { get; set; }
        public Nullable<int> ModCon_NoFB { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public Nullable<int> ModCon_NoMember_Target { get; set; }
        public Nullable<int> ModCon_NoMember { get; set; }
        public int iddModCon { get; set; }
        public Nullable<double> ModCon_unlined_target { get; set; }
        public Nullable<double> ModCon_unlined { get; set; }
        public Nullable<double> ModCon_lined_target { get; set; }
        public Nullable<double> ModCon_lined { get; set; }
        public Nullable<double> ModCon_SA { get; set; }
        [DisplayName("Service Area (ha)")]
        public Nullable<double> ModCon_SA_target { get; set; }
        public Nullable<double> ModCon_FUSA { get; set; }
        [DisplayName("FUSA (ha)")]
        public Nullable<double> ModCon_FUSA_target { get; set; }
        [DisplayName("Remarks")]
        public string ModCon_Remarks { get; set; }
        public Nullable<int> ModCon_NoIA_TARGET1 { get; set; }
        public Nullable<double> ModCon_Area_Covered_TARGET1 { get; set; }
        public Nullable<int> ModCon_NoFB_TARGET1 { get; set; }
        public Nullable<int> ModCon_NoMember_Target1 { get; set; }
        public Nullable<double> ModCon_unlined_target1 { get; set; }
        public Nullable<double> ModCon_lined_target1 { get; set; }
        public Nullable<double> ModCon_SA_target1 { get; set; }
        public Nullable<double> ModCon_FUSA_target1 { get; set; }
        public Nullable<int> ModCon_NoIA_TARGET2 { get; set; }
        public Nullable<double> ModCon_Area_Covered_TARGET2 { get; set; }
        public Nullable<int> ModCon_NoFB_TARGET2 { get; set; }
        public Nullable<int> ModCon_NoMember_Target2 { get; set; }
        public Nullable<double> ModCon_unlined_target2 { get; set; }
        public Nullable<double> ModCon_lined_target2 { get; set; }
        public Nullable<double> ModCon_SA_target2 { get; set; }
        public Nullable<double> ModCon_FUSA_target2 { get; set; }
    }
}
