//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_CapacityIA
    {
        public string IDAccomp { get; set; }
        public Nullable<int> CapacityIA_NoIA_TARGET { get; set; }
        public Nullable<int> CapacityIA_Batches_TARGET { get; set; }
        public Nullable<int> CapacityIA_Participants_TARGET { get; set; }
        public Nullable<int> CapacityIA_NoIA { get; set; }
        public Nullable<int> CapacityIA_Batches_Covered { get; set; }
        public Nullable<int> CapacityIA_Participants { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idc { get; set; }
        public Nullable<double> CapacityIA_COST { get; set; }
        public Nullable<double> CapacityIA_COST_TARGET { get; set; }
        public Nullable<int> CapacityIA_NoIA_TARGETAnnual { get; set; }
        public Nullable<int> CapacityIA_Batches_TARGETAnnual { get; set; }
        public Nullable<int> CapacityIA_Participants_TARGETAnnual { get; set; }
        public Nullable<double> CapacityIA_COST_TARGETAnnual { get; set; }
        public Nullable<int> CapacityIA_NoIA_TARGETRevised { get; set; }
        public Nullable<int> CapacityIA_Batches_TARGETRevised { get; set; }
        public Nullable<int> CapacityIA_Participants_TARGETRevised { get; set; }
        public Nullable<double> CapacityIA_COST_TARGETRevised { get; set; }
    }
}
