//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_Financial
    {
        public string IDAccomp { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        public Nullable<int> Particulars { get; set; }
        public Nullable<int> subParticulars { get; set; }
        public Nullable<double> Total_budget { get; set; }
        public Nullable<double> Total_Expenses { get; set; }
        public string quarter { get; set; }
        public int imtssFinancialID { get; set; }
    }
}
