//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_PS
    {
        public string IDAccomp { get; set; }
        public Nullable<double> salaries { get; set; }
        public Nullable<double> remunerations { get; set; }
        public Nullable<double> salaries_budget { get; set; }
        public Nullable<double> remunerations_budget { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
    }
}
