//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class IMTSS_Physical
    {
        public string IDAccomp { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public Nullable<System.DateTime> as_of { get; set; }
        [DisplayName("PARTICULARS")]
        public Nullable<int> Particulars { get; set; }
        [DisplayName("SUBPARTICULARS")]
        public Nullable<int> subParticulars { get; set; }
        [DisplayName("OTHER PARTICULARS")]
        public Nullable<int> subsubparticulars { get; set; }
        [DisplayName("TARGET FOR THE YEAR")]
        public Nullable<double> total_for_year { get; set; }
        [DisplayName("TARGET FOR THE MONTH")]
        public Nullable<double> target_actual { get; set; }
        [DisplayName("ACTUAL ACCOMPLISHMENT")]
        public Nullable<double> accomp_actual { get; set; }
        public string quarter { get; set; }
        public int imtssID { get; set; }
    }


   
}
