//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_CapacityIAWORKSHOP
    {
        public string IDAccomp { get; set; }
        public Nullable<double> CapacityIAWORKSHOP_COST_TARGET { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET { get; set; }
        public Nullable<double> CapacityIAWORKSHOP_COST { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Batches_Covered { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Participants { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idcC { get; set; }
        public Nullable<double> CapacityIAWORKSHOP_COST_TARGET1 { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET1 { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET1 { get; set; }
        public Nullable<double> CapacityIAWORKSHOP_COST_TARGET2 { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Batches_TARGET2 { get; set; }
        public Nullable<int> CapacityIAWORKSHOP_Participants_TARGET2 { get; set; }
    }
}
