//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_Model1
    {
        public string IDAccomp { get; set; }
        public Nullable<int> Mod1_NoIA_TARGET { get; set; }
        public Nullable<double> Mod1_Area_Covered_TARGET { get; set; }
        public Nullable<int> Mod1_NoFB_TARGET { get; set; }
        public Nullable<int> Mod1_NoIA { get; set; }
        public Nullable<double> Mod1_Area_Covered { get; set; }
        public Nullable<int> Mod1_NoFB { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idi { get; set; }
        public Nullable<int> Mod1_NoMember { get; set; }
        public Nullable<int> Mod1_NoMember_TARGET { get; set; }
    }
}
