//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMTSS_IAOrganization
    {
        public string IDAccomp { get; set; }
        public Nullable<int> Org_NoIA_TARGET { get; set; }
        public Nullable<double> Org_Area_Covered_TARGET { get; set; }
        public Nullable<int> Org_NoFB_TARGET { get; set; }
        public Nullable<int> Org_NoIA { get; set; }
        public Nullable<double> Org_Area_Covered { get; set; }
        public Nullable<int> Org_NoFB { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> year_covered { get; set; }
        public string as_of { get; set; }
        public int idd { get; set; }
        public Nullable<int> Org_NoMember_Target { get; set; }
        public Nullable<int> Org_NoMember { get; set; }
        public Nullable<int> Org_NoIA_TARGET1 { get; set; }
        public Nullable<double> Org_Area_Covered_TARGET1 { get; set; }
        public Nullable<int> Org_NoFB_TARGET1 { get; set; }
        public Nullable<int> Org_NoMember_Target1 { get; set; }
        public Nullable<int> Org_NoIA_TARGET2 { get; set; }
        public Nullable<double> Org_Area_Covered_TARGET2 { get; set; }
        public Nullable<int> Org_NoFB_TARGET2 { get; set; }
        public Nullable<int> Org_NoMember_Target2 { get; set; }
    }
}
