//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCARequest
    {
        public string IDAccomp { get; set; }
        public int IDNCARequest { get; set; }
        public string ASANo { get; set; }
        public Nullable<double> ASAAmount { get; set; }
        public Nullable<double> RequestAmount { get; set; }
        public Nullable<System.DateTime> dteRequest { get; set; }
        public Nullable<System.TimeSpan> timeRequest { get; set; }
        public string hashcode { get; set; }
        public string Description { get; set; }
    }
}
