//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAccompSummaryLog
    {
        public int IDSum { get; set; }
        public Nullable<int> IDPhysical { get; set; }
        public string IDAccomp { get; set; }
        public string FieldName { get; set; }
        public string Comp { get; set; }
        public Nullable<System.DateTime> datelog { get; set; }
        public Nullable<System.TimeSpan> timelog { get; set; }
        public string type { get; set; }
    }
}
