//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAccompBaseline
    {
        public string IDAccomp { get; set; }
        public int IDPhysical { get; set; }
        public Nullable<int> newarea { get; set; }
        public Nullable<int> restorearea { get; set; }
        public Nullable<int> rehabarea { get; set; }
        public Nullable<double> canalsaccomp { get; set; }
        public Nullable<double> canal_liningaccomp { get; set; }
        public Nullable<double> structuresaccomp { get; set; }
        public Nullable<double> roadsaccomp { get; set; }
        public Nullable<int> fbaccomp { get; set; }
        public Nullable<int> jobsaccomp { get; set; }
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string remarksAccomp { get; set; }
        public Nullable<double> Physical { get; set; }
        public Nullable<double> Financial { get; set; }
        public Nullable<double> ValueAccomp { get; set; }
        public Nullable<double> Expenditures { get; set; }
        public Nullable<double> HDPEACCOMP { get; set; }
        public Nullable<double> COCONETACCOMP { get; set; }
        public Nullable<double> GRAVELACCOMP { get; set; }
    }
}
