//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PhysicalAccomp
    {
        public string IDAccomp { get; set; }
        public int IDPhysical { get; set; }
            [DisplayName("NEW")]
        public Nullable<double> newarea { get; set; }
            [DisplayName("RESTORE")]
        public Nullable<double> restorearea { get; set; }
            [DisplayName("REHAB")]
        public Nullable<int> rehabarea { get; set; }
             [DisplayName("CANAL (km.)")]
        public Nullable<double> canalsaccomp { get; set; }
             [DisplayName("CANAL LINING (km.)")]
        public Nullable<double> canal_liningaccomp { get; set; }
            [DisplayName("STRUCTURE")]
        public Nullable<double> structuresaccomp { get; set; }
            [DisplayName("ROAD")]
        public Nullable<double> roadsaccomp { get; set; }
            [DisplayName("FARMER BENEFICIARIES")]
        public Nullable<int> fbaccomp { get; set; }
            [DisplayName("JOBS")]
        public Nullable<int> jobsaccomp { get; set; }
        [DisplayName("MONTH / YEAR")]
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("REMARKS")]
        public string remarksAccomp { get; set; }
        [DisplayName("PHYSICAL (%)")]
        public Nullable<double> Physical { get; set; }
        [DisplayName("FINANCIAL (%)")]
        public Nullable<double> Financial { get; set; }
       [DisplayName("VALUE ACCOMPLISHMENT")]
        public Nullable<double> ValueAccomp { get; set; }
        [DisplayName("EXPENDITURES")]
        public Nullable<double> Expenditures { get; set; }
        [DisplayName("HDPE (km.)")]
        public Nullable<double> HDPEACCOMP { get; set; }
        [DisplayName("COCONET (sq. m.)")]
        public Nullable<double> COCONETACCOMP { get; set; }
        [DisplayName("GRAVEL (km.)")]
        public Nullable<double> GRAVELACCOMP { get; set; }
        [DisplayName("PHYSICAL TARGET (%)")]
        public Nullable<double> physicaltarget { get; set; }
        public Nullable<double> physicaltargetvalueaccomp { get; set; }
        
    }
}
