//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Pow_View
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        public string mainproject { get; set; }
        public string subproject { get; set; }
        public string subsubproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> newed { get; set; }
        public Nullable<int> restored { get; set; }
        public Nullable<int> rehab { get; set; }
        public Nullable<double> canals { get; set; }
        public Nullable<double> canal_lining { get; set; }
        public Nullable<double> structures { get; set; }
        public Nullable<double> roads { get; set; }
        public Nullable<int> farmer_beneficiaries { get; set; }
        public Nullable<int> jobs { get; set; }
        public string remarks { get; set; }
        public Nullable<double> HDPE { get; set; }
        public Nullable<double> COCONET { get; set; }
        public Nullable<double> GRAVEL { get; set; }
        public Nullable<double> HDPEACCOMP { get; set; }
        public Nullable<double> COCONETACCOMP { get; set; }
        public Nullable<double> GRAVELACCOMP { get; set; }
        public string id_Main { get; set; }
        [DisplayName("PROJECT TITLE")]
        public string projectTitle { get; set; }
        [DisplayName("PROJECT DESCRIPTION")]
        public string projectDescription { get; set; }
        [DisplayName("PROGRAM NO.")]
        public string progNo { get; set; }
        public int powYear { get; set; }
        [DisplayName("DATE")]
        public Nullable<System.DateTime> powDate { get; set; }
        [DisplayName("Service Area/ Designed Area (Ha.)")]
        public double serviceArea { get; set; }
        [DisplayName("Source")]
        public string waterSource { get; set; }
        [DisplayName("Drainage Area")]
        public double drainageArea { get; set; }
        [DisplayName("Dependable Area")]
        public double dependArea { get; set; }
        public string rotr_Latitude { get; set; }
        public string rotr_Longitude { get; set; }
        public string reservoir_Latitude { get; set; }
        public string reservoir_Longitude { get; set; }
        public string gwp_Latitude { get; set; }
        public string gwp_Longitude { get; set; }
        public string other_typeOfIrrig { get; set; }
        public string other_Latitude { get; set; }
        public string other_Longitude { get; set; }
        [DisplayName("GOP")]
        public double opc_origGOP { get; set; }
        public double opc_revGOP { get; set; }
        [DisplayName("Loan Proceeds")]
        public double opc_origLP { get; set; }
        public double opc_revLP { get; set; }
        [DisplayName("LGU")]
        public double opc_origLGU { get; set; }
        public double opc_revLGU { get; set; }
        [DisplayName("IA")]
        public double opc_origIA { get; set; }
        public double opc_revIA { get; set; }
        [DisplayName("Other")]
        public string opc_Other { get; set; }
        public double opc_origOther { get; set; }
        public double opc_revOther { get; set; }
        public double main_new { get; set; }
        public double main_restored { get; set; }
        public double main_earthCanal { get; set; }
        public double main_lineCanal { get; set; }
        public double main_structure { get; set; }
        public double main_coconet { get; set; }
        public double main_roads { get; set; }
        public double main_gravel { get; set; }
        public string main_Repair { get; set; }
        public double main_RepairValue { get; set; }
        public double main_rehab { get; set; }
        public string main_Activity { get; set; }
        public double main_ActivityValue { get; set; }
        [DisplayName("Physical Starting Date")]
        public Nullable<System.DateTime> origDateStart { get; set; }
         [DisplayName("Completion Date")]
        public Nullable<System.DateTime> origDateEnd { get; set; }
       
        public Nullable<System.DateTime> revDateStart { get; set; }
        public Nullable<System.DateTime> revDateEnd { get; set; }
        public int id_work { get; set; }
        [DisplayName("Contract Works")]
        public double contract { get; set; }
        [DisplayName("Force Account Works")]
        public double forceAccount { get; set; }
        [DisplayName("Others")]
        public double otherWorks { get; set; }
        [DisplayName("Starting Date")]
        public Nullable<System.DateTime> workStart { get; set; }
        [DisplayName("No. of Days to Complete")]
        public int daysComplete { get; set; }
        [DisplayName("New Area (ha.)")]
        public double work_new { get; set; }
        [DisplayName("Restored Area (Ha.)")]
        public double work_restored { get; set; }
        [DisplayName("Earth Canal (km.)")]
        public double work_earthCanal { get; set; }
        [DisplayName("Lined Canal (km.)")]
        public double work_lineCanal { get; set; }
        [DisplayName("Structures (Unit)")]
        public double work_structure { get; set; }
        [DisplayName("Coconet (sqm.)")]
        public double work_coconet { get; set; }
        [DisplayName("Concrete Roads")]
        public double work_roads { get; set; }
        [DisplayName("Earth/Gravel roads (km.)")]
        public double work_gravel { get; set; }
        [DisplayName("Other Repair Works")]
        public string work_Repair { get; set; }
        [DisplayName("Value")]
        public double work_RepairValue { get; set; }
        [DisplayName("Rehab Area (ha.)")]
        public double work_rehab { get; set; }
        [DisplayName("Other Activities")]
        public string work_Activity { get; set; }
        [DisplayName("Value")]
        public double work_ActivityValue { get; set; }
        public int id_breakdown { get; set; }
        public Nullable<double> cwField_NIA { get; set; }
        public double cwField_LGU { get; set; }
        public double cwField_IA { get; set; }
        public double cwCO_NIA { get; set; }
        public double cwCO_LGU { get; set; }
        public double cwCO_IA { get; set; }
        public double fawField_NIA { get; set; }
        public double fawField_LGU { get; set; }
        public double fawField_IA { get; set; }
        public double fawCO_NIA { get; set; }
        public double fawCO_LGU { get; set; }
        public double fawCO_IA { get; set; }
        public double field_devProg { get; set; }
        public double co_devProg { get; set; }
        public double field_conSurvey { get; set; }
        public double co_conSurvey { get; set; }
        public double field_parcelMap { get; set; }
        public double co_parcelMap { get; set; }
        public double field_rightOfWay { get; set; }
        public double co_rightOfWay { get; set; }
        public double field_procureEquip { get; set; }
        public double co_procureEquip { get; set; }
        public double field_fieldSupport { get; set; }
        public double co_fieldSupport { get; set; }
        public double field_consulting { get; set; }
        public double co_consulting { get; set; }
        public double field_taxes { get; set; }
        public double co_taxes { get; set; }
        public double field_contingencies { get; set; }
        public double co_contingencies { get; set; }
        public double field_GOP { get; set; }
        public double field_LP { get; set; }
        public double co_GOP { get; set; }
        public double co_LP { get; set; }
        [DisplayName("Run off the river")]
        public Nullable<bool> rotr_check { get; set; }
        [DisplayName("Reservoir")]
        public Nullable<bool> reservoir_check { get; set; }
        [DisplayName("Ground Water Pump")]
        public Nullable<bool> gwp_check { get; set; }
        [DisplayName("Others")]
        public Nullable<bool> other_check { get; set; }
        public Nullable<int> FileId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public Nullable<int> FileType { get; set; }
    }
}
