//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProjectIssuesView
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public int IDProblem { get; set; }
        [Required]
        [DisplayName("ISSUES / PROBLEMS")]
        public string problem { get; set; }
        public string Expr1 { get; set; }
          [DisplayName("EXPLANATION")]
        [DataType(DataType.MultilineText)]
        public string description { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string asof { get; set; }
          [DisplayName("DATE")]
        public Nullable<System.DateTime> dateencoded { get; set; }
        public string username { get; set; }
        public string subproject { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        public string mainproject { get; set; }
        public string municipality { get; set; }
        public Nullable<double> amount { get; set; }
        public string maindescription { get; set; }
        public string projectmonitor { get; set; }
        public string OperationRegion { get; set; }
        public string issuesdescription { get; set; }
        public string powerbiregion { get; set; }

    }
}
