//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProjectCoordinate
    {
        public string idaccomp { get; set; }
         [DisplayName("Latitude")]
        public string lati { get; set; }
          [DisplayName("Longitude")]
        public string longi { get; set; }
        public int idcoordinates { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("REMARKS")]
        public string Description { get; set; }
        public string status { get; set; }
    }
}
