//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProjectIssue
    {
        public int IDProblem { get; set; }
        public string problem { get; set; }
        public string Idaccomp { get; set; }
         [DataType(DataType.MultilineText)]
        public string description { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
        public string asof { get; set; }
        public Nullable<System.DateTime> dateencoded { get; set; }
        public string username { get; set; }
    }
}
