//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProjectStatusImplementationView
    {
        public string IDAccomp { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string subproject { get; set; }
        public string maindescription { get; set; }
        public string projectmonitor { get; set; }
           [DisplayName("AS OF")]
        public string asof { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }     
           [DisplayName("PROJECT STATUS")]
        public string statusProject { get; set; }
          [DataType(DataType.MultilineText)]
           [DisplayName("REMARKS")]
        public string remarksAccomp { get; set; }
        public int IDProject { get; set; }
    }
}
