//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class ProjectCoordinatesView
    {
           [DisplayName("Latitude")]
        public string lati { get; set; }
           [DisplayName("Longitude")]
        public string longi { get; set; }
        public int idcoordinates { get; set; }
        public string Description { get; set; }
        public Nullable<int> year { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
           [DisplayName("Suboroject")]
        public string subproject { get; set; }
        public string maindescription { get; set; }
        public string IDAccomp { get; set; }
        public int SORT { get; set; }
        public string status { get; set; }
        public string municipality { get; set; }
        public string isnum { get; set; }
    }
}
