//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyConsultant
    {
        public int IDStudyConsultant { get; set; }
        public Nullable<int> IDStudy { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string MIDNAME { get; set; }
        public string SUFIX { get; set; }
        public Nullable<int> POSITION { get; set; }
    }
}
