//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOW_Main
    {
        public string id_Main { get; set; }
        public string IDAccomp { get; set; }
        public string projectTitle { get; set; }
        public string projectDescription { get; set; }
        public string progNo { get; set; }
        public int powYear { get; set; }
        public Nullable<System.DateTime> powDate { get; set; }
        public double serviceArea { get; set; }
        public string waterSource { get; set; }
        public double drainageArea { get; set; }
        public double dependArea { get; set; }
        public string rotr_Latitude { get; set; }
        public string rotr_Longitude { get; set; }
        public string reservoir_Latitude { get; set; }
        public string reservoir_Longitude { get; set; }
        public string gwp_Latitude { get; set; }
        public string gwp_Longitude { get; set; }
        public string other_typeOfIrrig { get; set; }
        public string other_Latitude { get; set; }
        public string other_Longitude { get; set; }
        public Nullable<bool> rotr_check { get; set; }
        public Nullable<bool> reservoir_check { get; set; }
        public Nullable<bool> gwp_check { get; set; }
        public Nullable<bool> other_check { get; set; }
        public double opc_origGOP { get; set; }
        public double opc_revGOP { get; set; }
        public double opc_origLP { get; set; }
        public double opc_revLP { get; set; }
        public double opc_origLGU { get; set; }
        public double opc_revLGU { get; set; }
        public double opc_origIA { get; set; }
        public double opc_revIA { get; set; }
        public string opc_Other { get; set; }
        public double opc_origOther { get; set; }
        public double opc_revOther { get; set; }
        public double main_new { get; set; }
        public double main_restored { get; set; }
        public double main_earthCanal { get; set; }
        public double main_lineCanal { get; set; }
        public double main_structure { get; set; }
        public double main_coconet { get; set; }
        public double main_roads { get; set; }
        public double main_gravel { get; set; }
        public string main_Repair { get; set; }
        public double main_RepairValue { get; set; }
        public double main_rehab { get; set; }
        public string main_Activity { get; set; }
        public double main_ActivityValue { get; set; }
        public Nullable<System.DateTime> origDateStart { get; set; }
        public Nullable<System.DateTime> origDateEnd { get; set; }
        public Nullable<System.DateTime> revDateStart { get; set; }
        public Nullable<System.DateTime> revDateEnd { get; set; }
    }
}
