//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOW_Breakdown
    {
        public string id_Main { get; set; }
        public int id_breakdown { get; set; }
        public string IDAccomp { get; set; }
        public Nullable<double> cwField_NIA { get; set; }
        public double cwField_LGU { get; set; }
        public double cwField_IA { get; set; }
        public double cwCO_NIA { get; set; }
        public double cwCO_LGU { get; set; }
        public double cwCO_IA { get; set; }
        public double fawField_NIA { get; set; }
        public double fawField_LGU { get; set; }
        public double fawField_IA { get; set; }
        public double fawCO_NIA { get; set; }
        public double fawCO_LGU { get; set; }
        public double fawCO_IA { get; set; }
        public double field_devProg { get; set; }
        public double co_devProg { get; set; }
        public double field_conSurvey { get; set; }
        public double co_conSurvey { get; set; }
        public double field_parcelMap { get; set; }
        public double co_parcelMap { get; set; }
        public double field_rightOfWay { get; set; }
        public double co_rightOfWay { get; set; }
        public double field_procureEquip { get; set; }
        public double co_procureEquip { get; set; }
        public double field_fieldSupport { get; set; }
        public double co_fieldSupport { get; set; }
        public double field_consulting { get; set; }
        public double co_consulting { get; set; }
        public double field_taxes { get; set; }
        public double co_taxes { get; set; }
        public double field_contingencies { get; set; }
        public double co_contingencies { get; set; }
        public double field_GOP { get; set; }
        public double field_LP { get; set; }
        public double co_GOP { get; set; }
        public double co_LP { get; set; }
    }
}
