//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOW_Work
    {
        public string id_Main { get; set; }
        public int id_work { get; set; }
        public string IDAccomp { get; set; }
        public double contract { get; set; }
        public double forceAccount { get; set; }
        public double otherWorks { get; set; }
        public Nullable<System.DateTime> workStart { get; set; }
        public int daysComplete { get; set; }
        public double work_new { get; set; }
        public double work_restored { get; set; }
        public double work_earthCanal { get; set; }
        public double work_lineCanal { get; set; }
        public double work_structure { get; set; }
        public double work_coconet { get; set; }
        public double work_roads { get; set; }
        public double work_gravel { get; set; }
        public string work_Repair { get; set; }
        public double work_RepairValue { get; set; }
        public double work_rehab { get; set; }
        public string work_Activity { get; set; }
        public double work_ActivityValue { get; set; }
    }
}
