//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catchment
    {
        public string IDDAm { get; set; }
        public int IDCatachment { get; set; }
        public Nullable<double> SedimentVolume { get; set; }
        public Nullable<double> SedimentArea { get; set; }
        public Nullable<double> SurfaceArea { get; set; }
        public Nullable<double> CatchmentArea { get; set; }
        public Nullable<double> Cover { get; set; }
        public Nullable<double> LandUse { get; set; }
        public Nullable<int> YearCovered { get; set; }
    }
}
