//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DamInforamtion
    {
        public string IDDam { get; set; }
        public string DamName { get; set; }
        public string TypeDam { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
         [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<double> ConstructionCost { get; set; }
        public string WaterSource { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string Municipality { get; set; }
        public string Description { get; set; }
        [DisplayName("YEAR")]
        public Nullable<int> YearCovered { get; set; }
        public int IDAppurtenance { get; set; }
        [DisplayName("Type")]
        public string SpillwayType { get; set; }
        [DisplayName("Dimension")]
        public string SpillwayDimension { get; set; }
        [DisplayName("IDF/T")]
        public string SpillwayIDF { get; set; }
          [DisplayName("Type")]
        public string OutletType { get; set; }
          [DisplayName("Dimension")]
        public string OutletDimension { get; set; }
                 [DisplayName("IDF/T")]
        public string OutletIDF { get; set; }
        public int IDCatachment { get; set; }
           [DisplayName("Volume")]
        public Nullable<double> SedimentVolume { get; set; }
           [DisplayName("Area")]
        public Nullable<double> SedimentArea { get; set; }
           [DisplayName("MAXIMUM RESERVOIR SURFACE AREA (SQKM)")]
        public Nullable<double> SurfaceArea { get; set; }
           [DisplayName("CATCHMENT AREA (SQKM")]
        public Nullable<double> CatchmentArea { get; set; }
           [DisplayName("VEGETATION COVER (%)")]
        public Nullable<double> Cover { get; set; }
           [DisplayName("MAJOR LAND USE (Indicate if for farming, etc.)")]
        public Nullable<double> LandUse { get; set; }
        public int IDDamBody { get; set; }
           [DisplayName("STRUCTURAL/ HYDRAULIC HEIGHT(M)")]
        public Nullable<double> Structural { get; set; }
           [DisplayName("CREST LENGTH (M)")]
        public Nullable<double> CrestLength { get; set; }
           [DisplayName("RIVERBED ELEVATION (MASL)")]
        public Nullable<double> RiverbedElevation { get; set; }
           [DisplayName("CREST WIDTH (M)")]
        public Nullable<double> CrestWidth { get; set; }
           [DisplayName("RESERVOIR CAP. (CU.M.)")]
        public Nullable<double> ReservoirCapacity { get; set; }
           [DisplayName("UPSTREAM FACE")]
        public string SlopeUpstream { get; set; }
           [DisplayName("DOWNSTREAM FACE")]
        public string SlopeDownstream { get; set; }
           [DisplayName("SIZE (S/M/L)")]
        public string DamSize { get; set; }
           [DisplayName("HAZARD & RISK (LOW/SIGNIFICANT/HIGH)")]
        public string DamHazardRisk { get; set; }
        public Nullable<double> SA { get; set; }
           [DisplayName("Elevation of lowest streambed along dam axis (m)")]
        public Nullable<double> ElevationLowestStreambed { get; set; }
           [DisplayName("Height above lowest streambed (m)")]
        public Nullable<double> HeightLowestStreambed { get; set; }
           [DisplayName("Dam crest level (m)")]
        public Nullable<double> DamCrest { get; set; }
           [DisplayName("Normal Resrvoir level (m)")]
        public Nullable<double> NormalReservoir { get; set; }
           [DisplayName("Top of inactive storage (m)")]
        public Nullable<double> TopInactive { get; set; }
           [DisplayName("Maximum Reservoir level (with surcharge) (m)")]
        public Nullable<double> MaximumReservoir { get; set; }
           [DisplayName("Design Capacity (cms)")]
        public Nullable<double> SpillwayCapacity { get; set; }
           [DisplayName("Crest Length (m)")]
        public Nullable<double> SpillwayCrestlength { get; set; }
           [DisplayName("Crest level at ogee portion (m)")]
        public Nullable<double> SpillwayCrestLevel { get; set; }
           [DisplayName("Design discharge at canal intake (cms)")]
        public Nullable<double> OutletDesignDischarge { get; set; }
           [DisplayName("Conduit size (diameter) at canal intake (m)")]
        public Nullable<double> OutletConduitSize { get; set; }
           [DisplayName("Conduit Length (m)")]
        public Nullable<double> OutletConduitLength { get; set; }
           [DisplayName("Type")]
        public string DiversionType { get; set; }
           [DisplayName("Design Capacity (cms)")]
        public Nullable<double> DiversionDesignCapacity { get; set; }
           [DisplayName("Conduit Diameter (m)")]
        public Nullable<double> DiversionConduitDiameter { get; set; }
           [DisplayName("Conduit Length (m)")]
        public Nullable<double> DiversionConduitLength { get; set; }
        [DisplayName("Status")]
           public string status { get; set; }
    }
}
