//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DamEntities : DbContext
    {
        public DamEntities()
            : base("name=DamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeneralInformation> GeneralInformations { get; set; }
        public virtual DbSet<DamView> DamViews { get; set; }
        public virtual DbSet<HydrologicalData> HydrologicalDatas { get; set; }
        public virtual DbSet<TypeDam> TypeDams { get; set; }
        public virtual DbSet<TypeDiversion> TypeDiversions { get; set; }
        public virtual DbSet<TypeReservoirArea> TypeReservoirAreas { get; set; }
        public virtual DbSet<TypeReservoirCapacity> TypeReservoirCapacities { get; set; }
        public virtual DbSet<TypeReservoirElevation> TypeReservoirElevations { get; set; }
        public virtual DbSet<TypeSpillway> TypeSpillways { get; set; }
        public virtual DbSet<Appurtenance> Appurtenances { get; set; }
        public virtual DbSet<Catchment> Catchments { get; set; }
        public virtual DbSet<DamBody> DamBodies { get; set; }
        public virtual DbSet<InspectionReport> InspectionReports { get; set; }
        public virtual DbSet<Rehabilitation> Rehabilitations { get; set; }
        public virtual DbSet<DamInforamtion> DamInforamtions { get; set; }
        public virtual DbSet<DamInspection> DamInspections { get; set; }
        public virtual DbSet<DamRehabilitation> DamRehabilitations { get; set; }
        public virtual DbSet<InstrumentData> InstrumentDatas { get; set; }
        public virtual DbSet<InstrumentDataView> InstrumentDataViews { get; set; }
        public virtual DbSet<InstrumentReading> InstrumentReadings { get; set; }
        public virtual DbSet<InstrumentReadingView> InstrumentReadingViews { get; set; }
        public virtual DbSet<DamPic> DamPics { get; set; }
        public virtual DbSet<DamPicView> DamPicViews { get; set; }
    }
}
