//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class DamPicView
    {
        public int PicID { get; set; }
        public byte[] DamPic { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string mapLoc { get; set; }
        public string DamName { get; set; }
        public string TypeDam { get; set; }
        public string Location { get; set; }
        public string DamLongitude { get; set; }
        public string DamLatitude { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<double> ConstructionCost { get; set; }
        public string WaterSource { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string IDDam { get; set; }


        public IEnumerable<HttpPostedFileBase> File { get; set; }
    }
}
