//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class DamPic
    {
        public int PicID { get; set; }
        public string IDDam { get; set; }
        public byte[] DamPic1 { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string mapLoc { get; set; }

    }
}
