//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DamView
    {
        public string IDDam { get; set; }
         [DisplayName("Name of Dam")]
        public string DamName { get; set; }
         [DisplayName("Type of Dam (based on the function)")]
        public string TypeDam { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
         [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
         [DisplayName("Completion Date")]
        public string CompletionDate { get; set; }
         [DisplayName("Construction Cost")]
        public Nullable<double> ConstructionCost { get; set; }
         [DisplayName("Source of Water")]
        public string WaterSource { get; set; }
        public string DamType { get; set; }
          [DisplayName("Height above Streambed (m)")]
        public Nullable<double> HeightStreambed { get; set; }
          [DisplayName("Crest Elevation (m)")]
        public Nullable<double> CrestElevation { get; set; }
          [DisplayName("Crest Width (m)")]
        public Nullable<double> CrestWidth { get; set; }
          [DisplayName("Crest Length (m)")]
        public Nullable<double> CrestLength { get; set; }
          [DisplayName("Embankment")]
        public Nullable<double> Embankment { get; set; }
          [DisplayName("Drainage Area (ha)")]
        public Nullable<double> DrainageArea { get; set; }
          [DisplayName("Inflow Design Flood (m3/s)")]
        public Nullable<double> InflowDesignFlood { get; set; }
          [DisplayName("Flood Frequency (yrs)")]
        public Nullable<double> FloodFrequency { get; set; }
          [DisplayName("Ave. Annual Runoff (m3/s)")]
        public Nullable<double> AveAnnualRunoff { get; set; }
        public string DiversionType { get; set; }
          [DisplayName("Number and Size")]
        public Nullable<double> NumberAndSize { get; set; }
        public string Control { get; set; }
          [DisplayName("Design Capacity")]
        public Nullable<double> DesignCapacity { get; set; }
          [DisplayName("Top Sediment")]
        public Nullable<double> TopSediment { get; set; }
          [DisplayName("Top Conservation")]
        public Nullable<double> TopConservation { get; set; }
          [DisplayName("Maximum")]
        public Nullable<double> MaximumRes { get; set; }
          [DisplayName("Inactive Storage")]
        public Nullable<double> InactiveStorage { get; set; }
          [DisplayName("Conservation Storage")]
        public Nullable<double> ConservationStorage { get; set; }
          [DisplayName("Surcharge Storage")]
        public Nullable<double> SurchargeStorage { get; set; }
        public Nullable<double> Maximum { get; set; }
        public Nullable<double> Normal { get; set; }
        public Nullable<double> Minimum { get; set; }
          [DisplayName("Spillway Type")]
        public string SpillwayType { get; set; }
          [DisplayName("Crest Width")]
        public Nullable<double> CrestWidth_spillway { get; set; }
          [DisplayName("Crest Elevation")]
        public Nullable<double> CrestElevation_spillway { get; set; }
          [DisplayName("Design Capacity (m3/s)")]
        public Nullable<double> DesignCapacity_spillway { get; set; }
          [DisplayName("Type Dissipitator")]
        public string TypeDissipitator { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string Municipality { get; set; }
        public Nullable<int> IDHydro { get; set; }
        public Nullable<int> IDReservoirArea { get; set; }
        public Nullable<int> IDDamType { get; set; }
        public Nullable<int> IDReservoirCapacity { get; set; }
        public Nullable<int> IDReservoirElevation { get; set; }
        public Nullable<int> IDDiversion { get; set; }
        public Nullable<int> IDSpillway { get; set; }
        public string Description { get; set; }
     
    }
}
