//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class GeneralInformation
    {

        public string Region { get; set; }
        public string Province { get; set; }
        public string Municipality { get; set; }
        [DataType(DataType.MultilineText)]
        [DisplayName("Descriptions")]
        public string Description { get; set; }
        public string IDDam { get; set; }
        [DisplayName("Name of Dam")]
        public string DamName { get; set; }
        [DisplayName("Type of Dam (based on the function)")]
        public string TypeDam { get; set; }
        public string Location { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        [DisplayName("Completion Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> CompletionDate { get; set; }
        [DisplayName("Construction Cost")]
        public Nullable<double> ConstructionCost { get; set; }
        [DisplayName("Source of Water")]
        public string WaterSource { get; set; }
        [DisplayName("Searvice Area (ha)")]
        public Nullable<double> SA { get; set; }
        public string status { get; set; }

    }
}
