//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydrologicalData
    {
        public string IDDam { get; set; }
        public Nullable<double> DrainageArea { get; set; }
        public Nullable<double> InflowDesignFlood { get; set; }
        public Nullable<double> FloodFrequency { get; set; }
        public Nullable<double> AveAnnualRunoff { get; set; }
        public int IDHydro { get; set; }
    }
}
