//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionReport
    {
        public string IDDAm { get; set; }
        public int IDInspection { get; set; }
        public Nullable<System.DateTime> DamSafetyInspection { get; set; }
        public string TypeofInspection { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> YearCovered { get; set; }
    }
}
