//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentData
    {
        public string IDDam { get; set; }
        public int IDInstrument { get; set; }
        public Nullable<double> ElevationTip { get; set; }
        public Nullable<double> ElevationUpper { get; set; }
        public Nullable<double> ElevationLower { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Instrument { get; set; }
        public string WaterLocation { get; set; }
    }
}
