//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentReading
    {
        public Nullable<int> IDInstrument { get; set; }
        public int IDReading { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<System.TimeSpan> TimeRead { get; set; }
        public Nullable<double> DataRead { get; set; }
        public string DataNo { get; set; }
        public Nullable<double> DataX { get; set; }
        public Nullable<double> DataY { get; set; }
        public byte[] UploadedFile { get; set; }
        public Nullable<int> filetype { get; set; }
        public string contenttype { get; set; }
        public Nullable<int> YearCovered { get; set; }
    }
}
