//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rehabilitation
    {
        public string IDDam { get; set; }
        public int IDRehab { get; set; }
        public Nullable<System.DateTime> Daterehab { get; set; }
        public string NatureOfRevision { get; set; }
        public Nullable<int> YearCovered { get; set; }
    }
}
