//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDiversion
    {
        public string IDDam { get; set; }
        public string DiversionType { get; set; }
        public Nullable<double> NumberAndSize { get; set; }
        public string Control { get; set; }
        public Nullable<double> DesignCapacity { get; set; }
        public int IDDiversion { get; set; }
    }
}
