//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeReservoirArea
    {
        public string IDDam { get; set; }
        public Nullable<double> TopSediment { get; set; }
        public Nullable<double> TopConservation { get; set; }
        public Nullable<double> MaximumRes { get; set; }
        public int IDReservoirArea { get; set; }
    }
}
