//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDam
    {
        public string IDDam { get; set; }
        public string DamType { get; set; }
        public Nullable<double> HeightStreambed { get; set; }
        public Nullable<double> CrestElevation { get; set; }
        public Nullable<double> CrestWidth { get; set; }
        public Nullable<double> CrestLength { get; set; }
        public Nullable<double> Embankment { get; set; }
        public int IDDamType { get; set; }
    }
}
