//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSpillway
    {
        public string IDDam { get; set; }
        public string SpillwayType { get; set; }
        public Nullable<double> CrestWidth { get; set; }
        public Nullable<double> CrestElevation { get; set; }
        public Nullable<double> DesignCapacity { get; set; }
        public string TypeDissipitator { get; set; }
        public int IDSpillway { get; set; }
    }
}
