//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRecordEmployee
    {
        public int DailyRecordID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public Nullable<System.DateTime> datescan { get; set; }
        public Nullable<System.TimeSpan> timescan { get; set; }
        public string gate1 { get; set; }
        public Nullable<System.TimeSpan> gate1time { get; set; }
        public string guard { get; set; }
        public Nullable<System.TimeSpan> guardtime { get; set; }
        public Nullable<double> temp { get; set; }
        public string medical { get; set; }
        public Nullable<System.TimeSpan> medicaltime { get; set; }
    }
}
