//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkStatusView
    {
        public int ChecklistID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public string comor { get; set; }
        public string Office { get; set; }
        public string WA { get; set; }
        public string WAState { get; set; }
        public string OneNW { get; set; }
        public string TwoA { get; set; }
        public string TwoB { get; set; }
        public string TwoC { get; set; }
        public string TwoD { get; set; }
        public string TwoE { get; set; }
        public string TwoF { get; set; }
        public string TwoG { get; set; }
        public string TwoGState { get; set; }
        public string TwoH { get; set; }
        public string TwoHState { get; set; }
        public string TwoI { get; set; }
        public string TwoIState { get; set; }
        public string ThreeA { get; set; }
        public string ThreeB { get; set; }
        public string ThreeC { get; set; }
        public string ThreeD { get; set; }
        public string ThreeE { get; set; }
        public string ThreeF { get; set; }
        public string ThreeG { get; set; }
        public string ThreeH { get; set; }
        public string ThreeI { get; set; }
        public Nullable<double> FourTemperature { get; set; }
        public string FiveA { get; set; }
        public string FiveB { get; set; }
        public string FiveC { get; set; }
        public string FiveD { get; set; }
        public string FiveE { get; set; }
        public string FiveF { get; set; }
        public string FiveG { get; set; }
        public string FiveH { get; set; }
        public string FiveHState { get; set; }
        public string FiveI { get; set; }
        public string FiveIState { get; set; }
        public string FiveJ { get; set; }
        public string FiveJState { get; set; }
        public string SixDataPrivacy { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<System.TimeSpan> TimeTaken { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> IDEmployeeStatus { get; set; }
        public Nullable<System.DateTime> DateGiven { get; set; }
        public Nullable<System.TimeSpan> TimeGiven { get; set; }
        public string LockdownOffice { get; set; }
        public string Status { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> FortheDate { get; set; }
        public string medicalstat { get; set; }
        public string note { get; set; }
    }
}
