//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryLocationProvinceMunicipality
    {
        public long ID { get; set; }
        public string Municipality { get; set; }
        public int MunicipalityPk { get; set; }
        public string Province { get; set; }
        public int Provincepk { get; set; }
    }
}
