//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPAIPBP_YR_2021Entities : DbContext
    {
        public OPAIPBP_YR_2021Entities()
            : base("name=OPAIPBP_YR_2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VWLOCATION> VWLOCATIONs { get; set; }
        public virtual DbSet<inventoryLocationProvinceMunicipality> inventoryLocationProvinceMunicipalities { get; set; }
        public virtual DbSet<inventoryLocationRegionProvince> inventoryLocationRegionProvinces { get; set; }
        public virtual DbSet<inventoryLocationMunicipalityDistrict> inventoryLocationMunicipalityDistricts { get; set; }
    }
}
