//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWLOCATION
    {
        public int MunicipalityPk { get; set; }
        public string Municipality { get; set; }
        public Nullable<int> RegionPk { get; set; }
        public Nullable<int> ProvincePk { get; set; }
        public Nullable<int> DistrictPk { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Region { get; set; }
        public Nullable<int> CropCode { get; set; }
    }
}
