//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOARD
    {
        public Nullable<int> YEAR_COVERED { get; set; }
        public string IA_NAME { get; set; }
        public string BOARDNAME { get; set; }
        public string POSITION { get; set; }
        public string TINNO { get; set; }
        public string CONTACTNO { get; set; }
        public string GENDER { get; set; }
        public string OFFICER_POSITION { get; set; }
        public Nullable<int> NOTERM { get; set; }
        public Nullable<System.DateTime> DATETERM { get; set; }
        public string IDIA { get; set; }
        public int BOARDID { get; set; }
    }
}
