//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class CANALS_STATIONING
    {
        public Nullable<int> YEAR_COVERED { get; set; }
        [DisplayName("IA NAME")]
        public string IA_NAME { get; set; }
        public Nullable<int> SORT { get; set; }
        [DisplayName("TYPE OF CANAL")]
        public string TYPE_CANAL { get; set; }
        [DisplayName("NAME OF CANAL")]
        public string NAME_CANAL { get; set; }
        [DisplayName("LENGTH OF CANAL")]
        public string FROMLENGTH { get; set; }
        public string TOLENGTH { get; set; }
        public Nullable<double> LENGTH_CANAL { get; set; }
        public string IDIA { get; set; }
        public int CANALID { get; set; }
    }
}
