//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FSEntry
    {
          [Required]
         [DisplayName("CATEGORY")]
        public string Category { get; set; }
        public int FSId { get; set; }
          [Required]
        [DisplayName("YEAR")]
        public Nullable<int> Year_Covered { get; set; }
          [Required]
        [DisplayName("BASED")]
        public string Criteria { get; set; }
        [Required]
        [DisplayName("NO. OF IA")]
        public Nullable<int> NoIA { get; set; }
        
        public Nullable<double> Entry1 { get; set; }
        public Nullable<double> Entry2 { get; set; }
        public Nullable<double> Entry3 { get; set; }
        public Nullable<double> Entry4 { get; set; }
        public Nullable<double> Entry5 { get; set; }
           [DisplayName("TOTAL SCORE (100)")]
        public Nullable<double> TotalScore { get; set; }
           [DisplayName("OUTSTANDING %")]
        public Nullable<double> Entry1_Percent { get; set; }
        [DisplayName("VERY SATISFACTORY %")]
        public Nullable<double> Entry2_Percent { get; set; }
        [DisplayName("SATISFACTORY %")]
        public Nullable<double> Entry3_Percent { get; set; }

        [DisplayName("FAIR %")]
        public Nullable<double> Entry4_Percent { get; set; }
        [DisplayName("POOR %")]
        public Nullable<double> Entry5_Percent { get; set; }
        public string Region { get; set; }
    }
}
