//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IA_AREA
    {
        public string IA_NAME { get; set; }
        public Nullable<int> YEAR_COVERED { get; set; }
        public Nullable<int> PROVINCE { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public string MUNICIPALITY { get; set; }
        public Nullable<int> TSA_NO { get; set; }
        public Nullable<int> FARMERS { get; set; }
        public Nullable<int> FARMERS_FEMALE { get; set; }
        public Nullable<double> FUSA { get; set; }
        public Nullable<int> FB { get; set; }
        public Nullable<double> SERVICE_AREA { get; set; }
        public string MAIN { get; set; }
        public Nullable<double> OPERATIONAL { get; set; }
        public Nullable<double> NONOPERATIONAL { get; set; }
        public string IDIA { get; set; }
        public int IAAREAID { get; set; }
    }
}
