//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAListView
    {
        public string region { get; set; }
        public Nullable<int> SORT { get; set; }
        public string IAname { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string IDIA { get; set; }
        public string systemname { get; set; }
        public string systemID { get; set; }
        public Nullable<int> id_region { get; set; }
        public Nullable<int> ID_CATEGORY { get; set; }
    }
}
