//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAList
    {
        public string IAname { get; set; }
        public string IDIA { get; set; }
        public Nullable<int> region { get; set; }
        public Nullable<int> category { get; set; }
        public string systemname { get; set; }
        public string systemID { get; set; }
    }
}
