//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MappingDataSystemIA

    {
        public int IdPolygon { get; set; }
        public string geometry { get; set; }
        public string drawingtype { get; set; }
        public string farmerlot { get; set; }
        public string farmername { get; set; }
        public string id { get; set; }
        public string Iddam { get; set; }
        public Nullable<int> overlayid { get; set; }
        public Nullable<double> polygonarea { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> year_covered { get; set; }
    }
}
