//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class CovidEquipmentEmployee
    {
        public int CovidEquipmentID { get; set; }
        public Nullable<int> mnt { get; set; }
        public Nullable<int> yr { get; set; }
         [DisplayName("DATE")]
        public Nullable<System.DateTime> dateGiven { get; set; }
        [DisplayName("FACE MASK")]
        public string facemask { get; set; }
        [DisplayName("VITAMINS")]
        public string vitamins { get; set; }
        [DisplayName("ALCOHOL")]
        public string alcohol { get; set; }
        [DisplayName("EMPLOYEE ID")]
        public string employeeid { get; set; }
        [DisplayName("LASTNAME")]
        public string lname { get; set; }
        [DisplayName("FIRSTNAME")]
        public string fname { get; set; }
        [DisplayName("MIDDLENAME")]
        public string midname { get; set; }
        [DisplayName("FACE SHIELD")]
        public string faceshield { get; set; }
        [DisplayName("VITAMINS TRANCE")]
        public string trance { get; set; }
    }
}
