//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CovidSurvey
    {
        public int IDSurvey { get; set; }
         [DisplayName("CATEGORY")]
        public string PersonnelCategory { get; set; }
         [DisplayName("EMPLOYEE ID")]
        public string EmployeeID { get; set; }
       [Required]
       [DisplayName("LASTNAME")]
        public string Lname { get; set; }
        [Required]
        [DisplayName("FIRSTNAME")]
        public string Fname { get; set; }
         [DisplayName("MIDDLENAME")]
        public string Midname { get; set; }
         [DisplayName("SUFFIX")]
        public string Sufix { get; set; }
         [DisplayName("DATE")]
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<System.TimeSpan> TimeTaken { get; set; }
        public string Office { get; set; }
        public string ContactNo { get; set; }
        public string cough { get; set; }
        public string cold { get; set; }
        public string diarrhea { get; set; }
        public string bodyache { get; set; }
        public string headache { get; set; }
        [Required]
        public Nullable<double> temp { get; set; }
        public string breathing { get; set; }
        public string sore { get; set; }
        public string fatigue { get; set; }
        public string travelled { get; set; }
        public string travelWHere { get; set; }
        public string travelWhen { get; set; }
        public string travelInfectedArea { get; set; }
        public string directContact { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public string facemask { get; set; }
        public string vitamins { get; set; }
        public string alcohol { get; set; }
        public string faceshield { get; set; }
        public string trance { get; set; }
        public Nullable<int> newid { get; set; }
    }
}
