//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CovidActivityEmployee
    {
        public int IDActivityEmployee { get; set; }
               [DisplayName("PLACES")]
        public string CategoryPlace { get; set; }
               [DisplayName("TIME FROM")]
        public Nullable<System.DateTime> TimeFrom { get; set; }
        [DisplayName("TIME TO")]
        public Nullable<System.DateTime> TimeTo { get; set; }
        [DisplayName("DATE")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateTaken { get; set; }
        [DisplayName("REMARKS")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> dateEncoded { get; set; }
    }
}
