//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTenant
    {
        public int TenantID { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string midname { get; set; }
        public string contact { get; set; }
        public string Office { get; set; }
    }
}
