//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSMSReceivedConso
    {
        public int SMSEmployeeID { get; set; }
        public string smsNumber { get; set; }
        public string smsMessage { get; set; }
        public string smsName { get; set; }
    }
}
