//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EmployeeLocation
    {
        public int id { get; set; }
        public string EmployeeName { get; set; }
        public string Address { get; set; }
        public string image { get; set; }
        public string imagename { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> SG { get; set; }
        public string City { get; set; }

        public string Cp { get; set; }
        [MaxLength(120, ErrorMessage = "Description cannot be longer than 120 characters.")]
        public string sms { get; set; }
    }
}
