//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class 
        InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Inventory_view> Inventory_view { get; set; }
        public virtual DbSet<CoordinatesPerSystem> CoordinatesPerSystems { get; set; }
        public virtual DbSet<SYSTEMPICTURE> SYSTEMPICTURES { get; set; }
        public virtual DbSet<TblData> TblDatas { get; set; }
        public virtual DbSet<TblCategory> TblCategories { get; set; }
        public virtual DbSet<TblRegionLogin> TblRegionLogins { get; set; }
        public virtual DbSet<TblCropsplanted> TblCropsplanteds { get; set; }
        public virtual DbSet<TblDistrict> TblDistricts { get; set; }
        public virtual DbSet<TblDiversion> TblDiversions { get; set; }
        public virtual DbSet<TblIMO> TblIMOes { get; set; }
        public virtual DbSet<TblOCI> TblOCIs { get; set; }
        public virtual DbSet<TblProvince> TblProvinces { get; set; }
        public virtual DbSet<MAPPIC> MAPPICs { get; set; }
        public virtual DbSet<MappingDataview> MappingDataviews { get; set; }
        public virtual DbSet<SystemsProfile> SystemsProfiles { get; set; }
        public virtual DbSet<MappingDataSystem> MappingDataSystems { get; set; }
        public virtual DbSet<MappingDataSystemsView> MappingDataSystemsViews { get; set; }
        public virtual DbSet<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual DbSet<CityBoundary> CityBoundaries { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<EmployeeSMSReceived> EmployeeSMSReceiveds { get; set; }
        public virtual DbSet<EmployeeSMSReceivedConso> EmployeeSMSReceivedConsoes { get; set; }
        public virtual DbSet<CovidSurvey> CovidSurveys { get; set; }
        public virtual DbSet<EmployeeTenant> EmployeeTenants { get; set; }
        public virtual DbSet<EM_ERoster> EM_ERoster { get; set; }
        public virtual DbSet<EmployeeCategory> EmployeeCategories { get; set; }
        public virtual DbSet<CovidEquipmentEmployee> CovidEquipmentEmployees { get; set; }
        public virtual DbSet<CovidTrance> CovidTrances { get; set; }
        public virtual DbSet<CovidActivityEmployee> CovidActivityEmployees { get; set; }
        public virtual DbSet<CovidPlace> CovidPlaces { get; set; }
        public virtual DbSet<MAPInventory> MAPInventories { get; set; }

        public virtual DbSet<SystemProfileView> SystemProfileViews { get; set; }
        public virtual DbSet<SystemSelection> SystemSelections { get; set; }
    }
}
