//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAPInventory
    {
        public string SYSTEMS { get; set; }
        public Nullable<double> SERVICE_ORIGINAL { get; set; }
        public Nullable<double> SERVICE_FIRMED { get; set; }
        public Nullable<double> AREA_OPERATIONAL { get; set; }
        public Nullable<double> AREA_NONOPERATIONAL { get; set; }
        public int ID_CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string IDSYSTEM { get; set; }
    }
}
