//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class MAPPIC
    {
        public int IDtable { get; set; }
        public string IDsystem { get; set; }
        public byte[] MAPsystem { get; set; }
        public string MAPLOC { get; set; }
        //[Required(ErrorMessage="Please Select Image File")]
        public Nullable<int> imagesize { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }

        public IEnumerable<HttpPostedFileBase> File { get; set; }
    }
}
