//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingDataSystemsView
    {
        public string IDSystems { get; set; }
        public string Systems { get; set; }
        public string Region { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int IdPolygon { get; set; }
        public string geometry { get; set; }
        public string drawingtype { get; set; }
        public string farmerlot { get; set; }
        public string farmername { get; set; }
        public string id { get; set; }
        public Nullable<int> overlayid { get; set; }
        public Nullable<double> polygonarea { get; set; }
    }
}
