//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingDataview
    {
        public int IdPolygon { get; set; }
        public string geometry { get; set; }
        public string drawingtype { get; set; }
        public string farmerlot { get; set; }
        public string farmername { get; set; }
        public string id { get; set; }
        public string Iddam { get; set; }
        public Nullable<int> overlayid { get; set; }
        public Nullable<double> polygonarea { get; set; }
        public string SYSTEMS { get; set; }
        public string REGION { get; set; }
        public string PROVINCE { get; set; }
        public string MUNICIPALITY { get; set; }
        public Nullable<double> SERVICE_ORIGINAL { get; set; }
        public Nullable<double> PERMANENT { get; set; }
        public Nullable<double> CONVERTED_LAND { get; set; }
        public Nullable<double> SERVICE_FIRMED { get; set; }
        public Nullable<double> AREA_OPERATIONAL { get; set; }
        public Nullable<double> AREA_NONOPERATIONAL { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string IDSystem { get; set; }
    }
}
