//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSelection
    {
        public string SYSTEMS { get; set; }
        public string res_region { get; set; }
        public string IDSystem { get; set; }
        public Nullable<double> RESPONSIBILITY { get; set; }
        public Nullable<int> ID_CATEGORY { get; set; }
    }
}
