//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TblData
    {
        public Nullable<int> ID_DATA { get; set; }
        public Nullable<double> PROJECT { get; set; }
        [DisplayName("YEAR")]
        public Nullable<double> YEAR_COVERED { get; set; }
        [DisplayName("SYSTEM NAME")]
        public string SYSTEMS { get; set; }
        public Nullable<double> CATEGORY { get; set; }
        public Nullable<double> REGION { get; set; }
        public Nullable<double> PROVINCE { get; set; }
        public string MUNICIPALITY { get; set; }
        public Nullable<double> DISTRICT { get; set; }
        public Nullable<double> SERVICE_ORIGINAL { get; set; }
        public Nullable<double> SERVICE_FIRMED { get; set; }
        public Nullable<double> AREA_OPERATIONAL { get; set; }
        public Nullable<double> AREA_NONOPERATIONAL { get; set; }
        public Nullable<double> IRRIGATED_WET { get; set; }
        public Nullable<double> IRRIGATED_DRY { get; set; }
        public Nullable<double> BENEFITED_WET { get; set; }
        public Nullable<double> BENEFITED_DRY { get; set; }
        public Nullable<double> AVERAGE_YIELD { get; set; }
        public string DATE_CONSTRUCTED { get; set; }
        public Nullable<int> OCI { get; set; }
        public string SPECIFY_AGENCY { get; set; }
        public string REHAB_YEAR { get; set; }
        public string LOCAL_COUNTERPART { get; set; }
        public Nullable<double> LOCAL_COUNTERPART_AMOUNT { get; set; }
        public string FOREX { get; set; }
        public Nullable<double> FOREX_AMOUNT { get; set; }
        public string REHAB_PROJECT { get; set; }
        public Nullable<int> DIVERSION { get; set; }
        public string SPECIFIC_DIVERSION { get; set; }
        public string WATER_SUPPLY { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<int> CROPS { get; set; }
        public string REMARKS { get; set; }
        public string DATE_UPDATED { get; set; }
        public Nullable<double> NOSYSTEM { get; set; }
        public string AMORTIZING { get; set; }
        public Nullable<double> IRRIGATED_RATOONING { get; set; }
        public Nullable<double> BENEFITED_RATOONING { get; set; }
        public Nullable<double> AVERAGE_YIELD_DRY { get; set; }
        public Nullable<double> AVERAGE_YIELD_RATOONING { get; set; }
        public string REMARKS_REASON { get; set; }
        public Nullable<double> FARMERS_BENEFICIARIES { get; set; }
        public Nullable<double> CONVERTED_LAND { get; set; }
        public Nullable<double> PERMANENT { get; set; }
        public Nullable<double> THIRD_IRRIGATED { get; set; }
        public Nullable<double> THIRD_BENEFITED { get; set; }
        public Nullable<double> THIRD_AVERAGE { get; set; }
        public Nullable<double> RESPONSIBILITY { get; set; }
        public string IMO_RES { get; set; }
        public string spec { get; set; }
        public Nullable<double> LINED { get; set; }
        public Nullable<double> UNLINED { get; set; }
        public Nullable<double> NEWLY { get; set; }
        public string DAMTYPE { get; set; }
        public string SD { get; set; }
        public Nullable<double> newlyarea { get; set; }
        public string IDSystem { get; set; }
        public Nullable<double> iano { get; set; }
        public Nullable<double> iaarea { get; set; }
        public Nullable<double> iafb { get; set; }
        public Nullable<double> iamember { get; set; }
        public Nullable<double> main_total { get; set; }
        public Nullable<double> main_lined { get; set; }
        public Nullable<double> main_earth { get; set; }
        public Nullable<double> lateral_total { get; set; }
        public Nullable<double> lateral_lined { get; set; }
        public Nullable<double> lateral_earth { get; set; }
        public Nullable<int> municipalityCode { get; set; }
        public Nullable<int> provinceCode { get; set; }

        [DisplayName("DAM NAME")]
        public string dam { get; set; }
    

    }
}
