//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIMO
    {
        public int ID { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string IMO { get; set; }
        public string ENG { get; set; }
        public string RIM { get; set; }
        public Nullable<int> res { get; set; }
        public string area_monitor { get; set; }
    }
}
