//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProvince
    {
        public int ID_PROVINCE { get; set; }
        public Nullable<int> ID_REGION { get; set; }
        public string PROVINCE { get; set; }
        public Nullable<int> ID_POLITICAL { get; set; }
        public Nullable<double> POP { get; set; }
        public Nullable<double> potential { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<double> C3019 { get; set; }
    }
}
