//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__vw_idtr
    {
        public string empno { get; set; }
        public string PDS_ID { get; set; }
        public Nullable<decimal> NewID { get; set; }
        public string status { get; set; }
        public string HasDTRID { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string suffix { get; set; }
        public string CurrentPosition { get; set; }
        public string CurrentOffice { get; set; }
        public string CurrentRate { get; set; }
        public string userid { get; set; }
        public string userpass { get; set; }
        public string hashcode { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> pdsdatetimeadded { get; set; }
        public Nullable<System.DateTime> SRFROM { get; set; }
        public string CurrentPositionOld { get; set; }
        public string srdesignation { get; set; }
        public string CurrentOfficeOld { get; set; }
        public string srplace { get; set; }
        public string CurrentRateOld { get; set; }
        public string salary { get; set; }
    }
}
