//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDSWebEntities : DbContext
    {
        public PDSWebEntities()
            : base("name=PDSWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PDS_Personalinfo_Active> PDS_Personalinfo_Active { get; set; }
        public virtual DbSet<C__vw_idtr> C__vw_idtr { get; set; }
        public virtual DbSet<PDS_Personalinfo_Active_QR> PDS_Personalinfo_Active_QR { get; set; }
    }
}
