//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_Personalinfo_Active
    {
        public int ID { get; set; }
        public string CSID { get; set; }
        public string empno { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string suffix { get; set; }
        public string fullname { get; set; }
        public string Raddress { get; set; }
        public string RadUnit { get; set; }
        public string RadStreet { get; set; }
        public string RadVillage { get; set; }
        public string RadBarangay { get; set; }
        public string RadCity { get; set; }
        public string RadProvince { get; set; }
        public string PadUnit { get; set; }
        public string PadStreet { get; set; }
        public string PadVillage { get; set; }
        public string PadBarangay { get; set; }
        public string PadCity { get; set; }
        public string PadProvince { get; set; }
        public string RAddressLocation { get; set; }
        public string RAddressZip { get; set; }
        public string RAddressTel { get; set; }
        public string municipality { get; set; }
        public string gender { get; set; }
        public string Citizenship { get; set; }
        public string CitiFilipino { get; set; }
        public string CitiDual { get; set; }
        public string CitiBirth { get; set; }
        public string CitiNatural { get; set; }
        public string CitiCountry { get; set; }
        public string civilstatus { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string placeofbirth { get; set; }
        public string celno { get; set; }
        public string bloodtype { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string gsis { get; set; }
        public string sss { get; set; }
        public string tin { get; set; }
        public string phil { get; set; }
        public string pagibig { get; set; }
        public string email { get; set; }
        public string Paddress { get; set; }
        public string PLocation { get; set; }
        public string PZip { get; set; }
        public string PTel { get; set; }
        public string Position { get; set; }
        public string Added { get; set; }
        public string TempEmpno { get; set; }
        public System.DateTime datetimeadded { get; set; }
        public string DTRid { get; set; }
        public string SR_id { get; set; }
        public string New_ID { get; set; }
        public Nullable<System.DateTime> seperationdate { get; set; }
        public string seperationcause { get; set; }
        public string tempActiveSR { get; set; }
        public string tempActivePDS { get; set; }
        public string PTelw { get; set; }
        public string residential_type_old { get; set; }
        public Nullable<double> IdNumber_Old { get; set; }
        public string sms_confirmed_smsnumber { get; set; }
        public string typehome2 { get; set; }
        public string residential_type { get; set; }
        public string smsName { get; set; }
        public string smsMessage { get; set; }
        public string final_celno { get; set; }
        public string sr_position { get; set; }
        public string Verified_Number { get; set; }
        public Nullable<System.DateTime> smsdate { get; set; }
        public Nullable<System.DateTime> Online_Contact_Updated { get; set; }
        public string srdesignation { get; set; }
        public string srstatus { get; set; }
        public string srplace { get; set; }
        public Nullable<int> SG { get; set; }
        public string salary { get; set; }
        public Nullable<System.DateTime> SRFROM { get; set; }
        public Nullable<decimal> IdNumber { get; set; }
    }
}
