//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_Personalinfo_Active_QR
    {
        public Nullable<int> ID { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string suffix { get; set; }
        public string Added { get; set; }
        public string DTRid { get; set; }
        public string SR_id { get; set; }
        public string IdNumber_old { get; set; }
        public string office { get; set; }
        public string PDSid { get; set; }
        public string celno { get; set; }
        public string IdNumber { get; set; }
        public Nullable<int> same_id_check { get; set; }
        public string final_celno { get; set; }
        public string region { get; set; }
    }
}
