//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementStandardDocumentView
    {
        public int StandardIDDocu { get; set; }
        public string Procurementmode { get; set; }
        public Nullable<int> IDDocument { get; set; }
        public string documentDescription { get; set; }
        public string lowestbidder { get; set; }
    }
}
