//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementSupplierQuotation
    {
        public int QuotationID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StatID { get; set; }
        public string remarks { get; set; }
        public string SupplierQuotation { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> totalBidPrice { get; set; }
    }
}
