//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementListForSupplier
    {
        public long ID { get; set; }
        public string ProcurementID { get; set; }
        public Nullable<double> qty { get; set; }
        public string procurementmode { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public string quotationno { get; set; }
        public string requisitionno { get; set; }
        public Nullable<System.DateTime> openingdate { get; set; }
        public Nullable<System.TimeSpan> openingtime { get; set; }
        public string philgeps { get; set; }
        public string notes { get; set; }
        public Nullable<int> deliveryPeriod { get; set; }
        public Nullable<int> validityPeriod { get; set; }
        public string article { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<int> supplierid { get; set; }
        public string supplieridstring { get; set; }
        public string draft { get; set; }

    }

}
