//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementPerSupplierDocument
    {
        public int IDSupplierDocu { get; set; }
        public string userid { get; set; }
        public Nullable<int> DOcuID { get; set; }
        public string Filename { get; set; }
        public string Filetype { get; set; }
    }
}
