//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementSupplierProcurementIDView
    {
        public long ID { get; set; }
        public string SuplierName { get; set; }
        public int SupplierID { get; set; }
        public string Address { get; set; }
        public string ProcurementID { get; set; }
        public string ContactNo { get; set; }
        public string PONumber { get; set; }
        public string WordedAmount { get; set; }
        public string statusbid { get; set; }
        public string userid { get; set; }
        public string draft { get; set; }
    }
}
