//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementSupplierProfile
    {
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string ContactNo { get; set; }
        public string userid { get; set; }
        public string Appoved { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public int SupID { get; set; }
        public string status { get; set; }

        public string region { get; set; }
    }
}
