//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class procurementss_onlinejervyEntities : DbContext
    {
        public procurementss_onlinejervyEntities()
            : base("name=procurementss_onlinejervyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProcurementSupplier> ProcurementSuppliers { get; set; }
        public virtual DbSet<ProcurementCartApprovedViewSum> ProcurementCartApprovedViewSums { get; set; }
        public virtual DbSet<ProcurementSupplierProfile> ProcurementSupplierProfiles { get; set; }
        public virtual DbSet<ProcurementListForSupplier> ProcurementListForSuppliers { get; set; }
        public virtual DbSet<ProcurementModeCartApproved> ProcurementModeCartApproveds { get; set; }
        public virtual DbSet<ProcurementSupplierQuotation> ProcurementSupplierQuotations { get; set; }
        public virtual DbSet<ProcurementSupplierQuotationView> ProcurementSupplierQuotationViews { get; set; }
        public virtual DbSet<ProcurementSupplierProcurementIDView> ProcurementSupplierProcurementIDViews { get; set; }
        public virtual DbSet<ProcurementFileDocument> ProcurementFileDocuments { get; set; }
        public virtual DbSet<ProcurementPerSupplierDocument> ProcurementPerSupplierDocuments { get; set; }
        public virtual DbSet<ProcurementDocument> ProcurementDocuments { get; set; }
        public virtual DbSet<ProcurementStandardDocumentView> ProcurementStandardDocumentViews { get; set; }
        public virtual DbSet<ProcurementAbstractofQuotation> ProcurementAbstractofQuotations { get; set; }
        public virtual DbSet<PRNOStatu> PRNOStatus { get; set; }
        public virtual DbSet<vwPRNODetailsJ> vwPRNODetailsJs { get; set; }
    }
}
