//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccompProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPRNODetailsJ
    {
        public int id { get; set; }
        public string ref_no { get; set; }
        public string pr_no { get; set; }
        public int id_key { get; set; }
        public string item_cat { get; set; }
        public string yr { get; set; }
        public string office_reg { get; set; }
        public string dept { get; set; }
        public string div { get; set; }
        public string sec { get; set; }
        public string date_created { get; set; }
        public string item_id { get; set; }
        public string proj_id { get; set; }
        public string item_desc { get; set; }
        public Nullable<double> qty { get; set; }
        public string unit_price { get; set; }
        public string total_price { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public string order_no { get; set; }
        public Nullable<bool> cart { get; set; }
        public string specs { get; set; }
    }
}
